import { test } from 'node:test';
import assert from 'node:assert/strict';
import { isRetryableGeminiError } from '../src/lib/veo.js';

/**
 * These tests classify transient errors that are safe to tolerate while
 * polling an already-submitted Veo operation. Classification must NOT be read
 * as permission to submit another generation request: AiWebVideo now stops a
 * production when a provider generation itself fails so it cannot silently
 * create duplicate billable video attempts.
 */

test('classifies a 429 RESOURCE_EXHAUSTED response as transient for same-operation polling', () => {
  const real = '{"error":{"code":429,"message":"You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. ","status":"RESOURCE_EXHAUSTED"}}';
  assert.equal(isRetryableGeminiError(real), true);
});

test('classifies another 429 provider response as transient for polling only', () => {
  const depleted = '{"error":{"code":429,"message":"Your prepayment credits are depleted. Please go to AI Studio at https://ai.studio/projects to manage your project and billing.","status":"RESOURCE_EXHAUSTED"}}';
  assert.equal(isRetryableGeminiError(depleted), true);
});

test('classifies transient service and network errors for continuing the same accepted operation', () => {
  assert.equal(isRetryableGeminiError('{"code":14,"message":"This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later."}'), true);
  assert.equal(isRetryableGeminiError('{"error":{"code":503,"status":"UNAVAILABLE","message":"The model is overloaded."}}'), true);
  assert.equal(isRetryableGeminiError('connect ETIMEDOUT 142.250.0.1:443'), true);
  assert.equal(isRetryableGeminiError('read ECONNRESET'), true);
});

test('recognizes the Veo processing-state response as transient', () => {
  const processing = '{"error":{"code":400,"message":"Input video must be a video that was generated by VEO that has been processed.","status":"INVALID_ARGUMENT"}}';
  assert.equal(isRetryableGeminiError(processing), true);
});

test('does not classify permanent/non-recoverable errors as transient', () => {
  assert.equal(isRetryableGeminiError('{"error":{"code":400,"status":"INVALID_ARGUMENT","message":"seed parameter is only supported in Gemini Enterprise Agent Platform mode"}}'), false);
  assert.equal(isRetryableGeminiError('{"error":{"code":403,"status":"PERMISSION_DENIED","message":"API key not valid"}}'), false);
  assert.equal(isRetryableGeminiError('No website screenshot is available for AI video grounding.'), false);
});
