import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  buildStoryboardPrompt,
  buildFallbackStoryboard,
  stableVariantSeed,
  isGenerativeVideoMode,
  type StoryboardInput,
  type StoryboardScene,
} from '../src/lib/gemini.js';
import { videoCreditCost, videoCreditQuote, normalizedGeneratedSeconds } from '../src/lib/credits.js';
import {
  VIDEO_MASTER_PROMPTS,
  GLOBAL_AI_VIDEO_RULES,
  buildAiVideoScenePrompt,
} from '../src/lib/video-prompts.js';

function plannerInput(overrides: Partial<StoryboardInput> = {}): StoryboardInput {
  return {
    siteUrl: 'https://example-store.com',
    pageTitle: 'Example Store | أصنافنا',
    description: 'A real storefront',
    screenshotBase64: null,
    fullPageScreenshotBase64: null,
    referenceCaptures: [
      { label: 'Homepage', base64: 'aGVsbG8=' },
      { label: 'Product page — real option selected', base64: 'd29ybGQ=' },
      { label: 'Added to cart', base64: 'cGFnZQ==' },
      { label: 'Shopping cart', base64: 'Y2FydA==' },
      { label: 'Checkout — real entry state', base64: 'Y2hlY2tvdXQ=' },
      { label: 'AI assistant / live chat', base64: 'Y2hhdA==' },
    ],
    mode: 'video',
    vibeBrief: 'Premium editorial',
    targetDurationSeconds: 24,
    featuresText: null,
    creativeBrief: null,
    aspectRatio: '16:9',
    outputQuality: '1080p',
    frameRate: 30,
    variationKey: 'job-a:1:seed-a',
    ...overrides,
  };
}

const MODE_SIGNATURES: Array<[StoryboardInput['mode'], string]> = [
  ['video', 'PROMO VIDEO — AI-generated premium website commercial'],
  ['tutorial', 'HOW TO USE — AI-generated first-time-user walkthrough'],
  ['buy', 'HOW TO BUY / CONVERT — AI-generated transaction journey'],
  ['tour', 'FEATURE TOUR — AI-generated feature-by-feature showcase'],
  ['demo', 'CINEMATIC BRAND FILM — fully AI-generated premium product film'],
  ['photos', 'PHOTOS — premium marketing image creation'],
  ['icon', 'WEBSITE ICON — four premium square brand-mark concepts'],
  ['both', 'VIDEO + PHOTOS — true AI-generated commercial plus creative marketing stills'],
  ['mockup', 'DIGITAL PRODUCT MOCKUP / MOTION GRAPHIC VIDEO — social-feed-style product reveal'],
  ['linkedin', 'LINKEDIN VIDEO — professional feed story'],
  ['custom', 'CUSTOM IDEA — the user\'s own concept, AI-directed'],
];

for (const [mode, signature] of MODE_SIGNATURES) {
  test(`${mode} mode sends its own master planner prompt`, () => {
    const { prompt } = buildStoryboardPrompt(plannerInput({ mode }));
    assert.ok(prompt.includes(signature), `expected ${mode} prompt to include "${signature}"`);
    assert.ok(prompt.includes(`MODE: ${mode}`));
  });
}

test('all video-producing modes explicitly plan true AI video', () => {
  for (const mode of ['video', 'tutorial', 'buy', 'tour', 'demo', 'both', 'mockup', 'linkedin', 'custom'] as const) {
    assert.equal(isGenerativeVideoMode(mode), true);
    const { prompt } = buildStoryboardPrompt(plannerInput({ mode }));
    assert.ok(prompt.includes('Every final video scene will be generated by an AI VIDEO model'));
    assert.ok(prompt.includes('Do not plan screenshot pans, Ken-Burns moves, code-drawn cursors, or slideshow transitions'));
    assert.ok(prompt.includes('sourceIndices select the real grounding state(s) for the AI video model'));
  }
});

test('AI-video planning protects real UI text and forbids fabricated states', () => {
  const { prompt } = buildStoryboardPrompt(plannerInput({ mode: 'buy' }));
  assert.ok(prompt.includes('Preserve visible Arabic/English wording'));
  assert.ok(prompt.includes('Never invent a product, page, feature, modal, cart state, checkout state'));
  assert.ok(prompt.includes('real BEFORE state first and the real AFTER state second'));
  assert.ok(prompt.includes('Never cut in the middle of the click or state change'));
});

test('buy master adapts ecommerce to SaaS/service/booking conversion journeys', () => {
  const { prompt } = buildStoryboardPrompt(plannerInput({ mode: 'buy' }));
  assert.ok(prompt.includes('storefront/category -> product -> option/size/color if captured -> add to cart -> cart -> checkout if captured'));
  assert.ok(prompt.includes('SaaS/service/booking sites'));
  assert.ok(prompt.includes('plan selection, booking, signup, or checkout'));
});

test('tutorial and feature tour discover supported real interactions', () => {
  const tutorial = buildStoryboardPrompt(plannerInput({ mode: 'tutorial' })).prompt;
  assert.ok(tutorial.includes('browse, search, filter, open item, choose option, use a tool, open chat'));
  const tour = buildStoryboardPrompt(plannerInput({ mode: 'tour' })).prompt;
  assert.ok(tour.includes('chat/AI assistant'));
  assert.ok(tour.includes('Long tours must keep introducing new content'));
});

test('duration policy keeps short clips complete and long films non-repetitive', () => {
  const shortPrompt = buildStoryboardPrompt(plannerInput({ targetDurationSeconds: 8 })).prompt;
  assert.ok(shortPrompt.includes('For 8-second videos, tell a complete micro-story'));
  assert.ok(shortPrompt.includes('Do not cram in unfinished steps'));
  const longPrompt = buildStoryboardPrompt(plannerInput({ targetDurationSeconds: 64 })).prompt;
  assert.ok(longPrompt.includes('For 48-64 seconds'));
  assert.ok(longPrompt.includes('no filler, no recycled feature, no identical motion loops'));
});

test('photos remain a separate AI image pipeline with UI-text protection', () => {
  const { prompt, isPhotos } = buildStoryboardPrompt(plannerInput({ mode: 'photos' }));
  assert.equal(isPhotos, true);
  assert.ok(prompt.includes('PHOTO MODE — CAPTURE-BASED CREATIVE EDITING'));
  assert.ok(prompt.includes('final marketing photos MAY be creatively transformed'));
  assert.ok(prompt.includes('never translate, correct, replace, or redraw that UI text'));
});

test('website icon mode plans four square brand-grounded concepts', () => {
  const { prompt, isPhotos, sceneCount } = buildStoryboardPrompt(plannerInput({ mode: 'icon', aspectRatio: '1:1' }));
  assert.equal(isPhotos, true);
  assert.equal(sceneCount, 4);
  assert.ok(prompt.includes('WEBSITE ICON MODE — SQUARE BRAND-IDENTITY CONCEPTS'));
  assert.ok(prompt.includes('favicon, mobile shortcut, social avatar, and branded video ending'));
  const fallback = buildFallbackStoryboard(plannerInput({ mode: 'icon', aspectRatio: '1:1' }));
  assert.equal(fallback.scenes.length, 4);
  assert.ok(fallback.scenes.every((scene) => scene.durationSeconds === 0 && scene.sourceIndices?.length === 0));
  assert.equal(videoCreditCost('icon', true, 56), 8);
});

test('video + photos keeps true AI video and creative AI photos separate', () => {
  const { prompt } = buildStoryboardPrompt(plannerInput({ mode: 'both' }));
  assert.ok(prompt.includes('VIDEO + PHOTOS — TWO AI PIPELINES'));
  assert.ok(prompt.includes('every scene is generated by the selected AI video model'));
  assert.ok(prompt.includes('PHOTO OUTPUT: may creatively transform'));
});

test('custom instructions supplement rather than replace the master rules', () => {
  const { prompt } = buildStoryboardPrompt(plannerInput({
    mode: 'video',
    creativeBrief: 'Focus on dresses and finish on the real checkout entry.',
  }));
  assert.ok(prompt.includes('Focus on dresses and finish on the real checkout entry.'));
  assert.ok(prompt.includes('PROMO VIDEO — AI-generated premium website commercial'));
  assert.ok(prompt.includes('AI VIDEO REFERENCE LOCK — REAL WEBSITE, GENERATED MOTION'));
});

test('prompt includes capture context, delivery format, duration and AI reference semantics', () => {
  const { prompt, captureCount, sceneCount } = buildStoryboardPrompt(plannerInput({ targetDurationSeconds: 24 }));
  assert.equal(captureCount, 6);
  assert.equal(sceneCount, 3);
  assert.ok(prompt.includes('Attached are 6 labeled real website screenshots'));
  assert.ok(prompt.includes('DELIVERY: 16:9, 1080p, 30 FPS'));
  assert.ok(prompt.includes('Create exactly 3 AI video scenes of 8 seconds each'));
});

test('runtime master prompts exist for every video feature', () => {
  for (const mode of ['video', 'tutorial', 'buy', 'tour', 'demo', 'both', 'mockup', 'linkedin', 'custom']) {
    assert.ok(VIDEO_MASTER_PROMPTS[mode]?.length > 120, `missing runtime master prompt for ${mode}`);
  }
  assert.ok(GLOBAL_AI_VIDEO_RULES.includes('Every scene must be a real video clip generated by the selected AI video provider'));
  assert.ok(GLOBAL_AI_VIDEO_RULES.includes('Never rewrite, translate, correct, relabel, respell, replace, or hallucinate visible website text'));
  assert.ok(GLOBAL_AI_VIDEO_RULES.includes('Never cut in the middle of a meaningful click'));
});

test('runtime interaction prompt requires a grounded completed action and suitable audio', () => {
  const scene: StoryboardScene = {
    sceneNumber: 1,
    durationSeconds: 8,
    sceneType: 'interaction',
    shotDescription: 'Use the real product state, click Add to Cart, and arrive at the real cart state.',
    sourceIndices: [1, 2],
    composition: 'single',
    motion: 'static',
    focusX: 0.5,
    focusY: 0.5,
    onScreenCopy: '',
    transition: '',
  };
  const prompt = buildAiVideoScenePrompt({
    mode: 'buy', siteTitle: 'Example Store', concept: 'purchase journey', vibe: 'premium', scene,
    sceneIndex: 0, totalScenes: 3, targetDurationSeconds: 24, nativeAudio: true,
    referenceLabels: ['Product page — real option selected', 'Added to cart'], variantSeed: 12, aspectRatio: '16:9',
  });
  assert.ok(prompt.includes('Generate a REAL moving AI-video clip'));
  assert.ok(prompt.includes('performing the real action'));
  assert.ok(prompt.includes('Hold the result long enough to read it'));
  assert.ok(prompt.includes('Generate native audio appropriate to this mode and scene'));
  assert.ok(!prompt.includes('GLOBAL_AI_VIDEO_RULES'));
  // Keep the per-scene execution prompt comfortably compact for video-model limits.
  assert.ok(prompt.length < 5200, `runtime scene prompt is too large: ${prompt.length} chars`);
});

test('square runtime prompt reserves the center safe area', () => {
  const scene: StoryboardScene = {
    sceneNumber: 1, durationSeconds: 8, sceneType: 'hook', shotDescription: 'Reveal the real homepage.', sourceIndices: [0],
    composition: 'single', motion: 'static', focusX: 0.5, focusY: 0.5, onScreenCopy: '', transition: '',
  };
  const prompt = buildAiVideoScenePrompt({
    mode: 'video', siteTitle: 'Example', concept: 'promo', vibe: 'clean', scene,
    sceneIndex: 0, totalScenes: 1, targetDurationSeconds: 8, nativeAudio: false, aspectRatio: '1:1',
  });
  assert.ok(prompt.includes('central square-safe area'));
});

test('music-only runtime prompt strictly forbids talking and vocals', () => {
  const scene: StoryboardScene = {
    sceneNumber: 1, durationSeconds: 8, sceneType: 'hook', shotDescription: 'Reveal the real homepage.', sourceIndices: [0],
    composition: 'single', motion: 'static', focusX: 0.5, focusY: 0.5, onScreenCopy: '', transition: '',
  };
  const prompt = buildAiVideoScenePrompt({
    mode: 'video', siteTitle: 'Example', concept: 'promo', vibe: 'clean', scene,
    sceneIndex: 0, totalScenes: 1, targetDurationSeconds: 8, nativeAudio: true, musicOnly: true,
  });
  assert.ok(prompt.includes('MUSIC ONLY'));
  assert.ok(prompt.includes('Absolutely no talking, narration, dialogue, vocals'));
});

test('variation key changes the seed and remains deterministic for the same key', () => {
  const a = buildStoryboardPrompt(plannerInput({ variationKey: 'job:1:version-a' }));
  const b = buildStoryboardPrompt(plannerInput({ variationKey: 'job:2:version-b' }));
  const a2 = buildStoryboardPrompt(plannerInput({ variationKey: 'job:1:version-a' }));
  assert.notEqual(a.variantSeed, b.variantSeed);
  assert.notEqual(a.prompt, b.prompt);
  assert.equal(a.variantSeed, a2.variantSeed);
  assert.ok(a.prompt.includes(`CREATIVE VARIATION ID: ${a.variantSeed}`));
  assert.equal(stableVariantSeed('job:1:version-a'), a.variantSeed);
});

test('fallback AI-video storyboard uses only real capture indexes and no generated copy', () => {
  const storyboard = buildFallbackStoryboard(plannerInput({ targetDurationSeconds: 24 }));
  assert.equal(storyboard.scenes.length, 3);
  assert.equal(storyboard.voiceoverScript, null);
  for (const scene of storyboard.scenes) {
    assert.equal(scene.durationSeconds, 8);
    assert.equal(scene.onScreenCopy, '');
    assert.equal(scene.composition, 'single');
    assert.equal(scene.motion, 'static');
    assert.ok((scene.sourceIndices ?? []).every((index) => index >= 0 && index < 6));
  }
});

test('fallback photo storyboard plans four creative images with no capture indexes', () => {
  const storyboard = buildFallbackStoryboard(plannerInput({ mode: 'photos' }));
  assert.equal(storyboard.scenes.length, 4);
  for (const scene of storyboard.scenes) {
    assert.deepEqual(scene.sourceIndices, []);
    assert.equal(scene.motion, 'static');
  }
});

test('two variation seeds produce different fallback reference choices', () => {
  const a = buildFallbackStoryboard(plannerInput({ variationKey: 'seed-one' }));
  const b = buildFallbackStoryboard(plannerInput({ variationKey: 'seed-two' }));
  assert.notEqual(a.variantSeed, b.variantSeed);
  assert.notDeepEqual(a.scenes.map((scene) => scene.sourceIndices), b.scenes.map((scene) => scene.sourceIndices));
});

test('mockup mode plans a fast social-feed-style product reveal, not a website tour', () => {
  const { prompt } = buildStoryboardPrompt(plannerInput({ mode: 'mockup' }));
  assert.ok(prompt.includes('social-feed-style product reveal'));
  assert.ok(prompt.includes('hook on the strongest page first'));
  assert.ok(prompt.includes('Every final video scene will be generated by an AI VIDEO model'));
  assert.ok(prompt.includes('scroll-stopping'));
});

test('mockup fallback storyboard flips through distinct real pages/panels', () => {
  const storyboard = buildFallbackStoryboard(plannerInput({ mode: 'mockup', targetDurationSeconds: 32 }));
  assert.equal(storyboard.scenes.length, 4);
  const descriptions = storyboard.scenes.map((scene) => scene.shotDescription);
  assert.equal(new Set(descriptions).size, descriptions.length, 'each mockup fallback scene should be a distinct direction');
  for (const scene of storyboard.scenes) assert.equal(scene.onScreenCopy, '');
});

test('custom mode lets the user\'s written brief drive the film while keeping AI-video and fidelity guardrails', () => {
  const { prompt } = buildStoryboardPrompt(plannerInput({
    mode: 'custom',
    creativeBrief: 'Show the product spinning slowly with dramatic red lighting, no people.',
  }));
  assert.ok(prompt.includes('Show the product spinning slowly with dramatic red lighting, no people.'));
  assert.ok(prompt.includes('is the actual brief for this film, not a generic template'));
  // Custom mode must still inherit the non-negotiable real-video/no-fabrication rules.
  assert.ok(prompt.includes('Every final video scene will be generated by an AI VIDEO model'));
  assert.ok(prompt.includes('Never invent a product, page, feature, modal, cart state, checkout state'));
});

test('mockup and custom are true AI-video modes with the standard per-second credit cost', () => {
  assert.equal(isGenerativeVideoMode('mockup'), true);
  assert.equal(isGenerativeVideoMode('custom'), true);
  assert.equal(videoCreditCost('mockup', true, 8), videoCreditCost('video', true, 8));
  assert.equal(videoCreditCost('custom', false, 24), videoCreditCost('video', false, 24));
});

test('twenty selected photos plan a complete 2m40s production without the old ten-reference cap', () => {
  const referenceCaptures = Array.from({ length: 20 }, (_, index) => ({
    label: `Selected customer photo ${index + 1}`,
    base64: Buffer.from(`photo-${index + 1}`).toString('base64'),
  }));
  const plan = buildStoryboardPrompt(plannerInput({ referenceCaptures, targetDurationSeconds: 160 }));
  assert.equal(plan.captureCount, 20);
  assert.equal(plan.sceneCount, 20);
  assert.ok(plan.prompt.includes('Use every selected page/photo reference at least once'));
  const fallback = buildFallbackStoryboard(plannerInput({ referenceCaptures, targetDurationSeconds: 160 }));
  assert.equal(fallback.scenes.length, 20);
  assert.equal(new Set(fallback.scenes.map((scene) => scene.sourceIndices?.[0])).size, 20);
});

test('custom video quotes cover every generated second up to four minutes', () => {
  assert.equal(normalizedGeneratedSeconds(10), 16, 'partial provider scenes round up safely');
  const long1080 = videoCreditQuote('video', false, 160, '1080p');
  assert.deepEqual(long1080, {
    generatedSeconds: 160, perSecondCredits: 1, videoCredits: 160,
    photoCredits: 0, narrationCredits: 6, totalCredits: 166,
  });
  const max4k = videoCreditQuote('video', true, 240, '4k');
  assert.equal(max4k.generatedSeconds, 240);
  assert.equal(max4k.totalCredits, 720);
  assert.equal(buildFallbackStoryboard(plannerInput({ targetDurationSeconds: 240 })).scenes.length, 30);
});
