import { GoogleGenAI } from '@google/genai';
import { recordGeminiTextUsage } from './costs.js';
import { runQueuedProviderCall } from './provider-queue.js';

let _client: GoogleGenAI | null = null;

function getClient(): GoogleGenAI {
  if (!_client) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('GEMINI_API_KEY environment variable is not set.');
    _client = new GoogleGenAI({ apiKey });
  }
  return _client;
}

export interface StoryboardScene {
  sceneNumber: number;
  durationSeconds: number;
  sceneType: 'hook' | 'feature' | 'interaction' | 'social_proof' | 'cta';
  shotDescription: string;
  /**
   * 0-based indexes into the capture list supplied to the planner. For every
   * video mode these are AI-video grounding references. Interaction scenes
   * should put the real before-state first and real after-state second.
   */
  sourceIndices?: number[];
  /** Legacy storyboard-shape fields kept for stored-job/client compatibility. AI video generation does not manufacture motion from them. */
  composition?: 'single' | 'sequence' | 'split' | 'triple';
  /** Legacy compatibility field; generated motion is described in shotDescription and created by the AI video provider. */
  motion?: 'push_in' | 'pull_out' | 'pan_left' | 'pan_right' | 'pan_up' | 'pan_down' | 'static';
  /** Legacy compatibility fields; the AI video renderer does not crop screenshots using them. */
  focusX?: number;
  focusY?: number;
  /** Always empty so generated website footage never adds or rewrites interface/campaign text. */
  onScreenCopy: string;
  transition: string;
}

export interface Storyboard {
  concept: string;
  vibe: string;
  ideas: string[];
  scenes: StoryboardScene[];
  /** Narration is disabled by default; audio treatment is handled separately. */
  voiceoverScript: string | null;
  targetDurationSeconds?: number;
  creativeBrief?: string;
  aspectRatio?: '16:9' | '9:16' | '1:1';
  outputQuality?: '1080p' | '4k';
  frameRate?: 24 | 30 | 60;
  /** Server-generated seed so each regeneration produces a genuinely new edit. */
  variantSeed?: number;
  /** Stable capture filenames explicitly selected by the customer. */
  selectedCaptureIds?: string[];
  /** Exact capture ids used by each scene, attached after planning. */
  sceneCaptureIds?: string[][];
}

const STORYBOARD_SCHEMA = {
  type: 'OBJECT' as const,
  properties: {
    concept: { type: 'STRING' as const, description: 'One-sentence production concept grounded in the captured website assets and the selected mode.' },
    vibe: { type: 'STRING' as const, description: 'The pacing and editorial mood.' },
    ideas: {
      type: 'ARRAY' as const,
      items: { type: 'STRING' as const },
      description: '3-5 alternate production ideas that obey the selected mode rules and customer brief.',
    },
    scenes: {
      type: 'ARRAY' as const,
      items: {
        type: 'OBJECT' as const,
        properties: {
          sceneNumber: { type: 'INTEGER' as const },
          durationSeconds: { type: 'NUMBER' as const },
          sceneType: {
            type: 'STRING' as const,
            enum: ['hook', 'feature', 'interaction', 'social_proof', 'cta'],
            description: 'Narrative role of the scene. For video, "interaction" means the AI should perform a real visible action grounded by before/after captures when available. Photos normally use hook/feature/cta.',
          },
          shotDescription: {
            type: 'STRING' as const,
            description: 'Shot or image art direction grounded in the captured website references and selected mode.',
          },
          sourceIndices: {
            type: 'ARRAY' as const,
            items: { type: 'INTEGER' as const },
            description: 'CUSTOM/SCENARIO VIDEO: up to 3 zero-based CAPTURE indexes may be used as Veo asset references for subject/product/place/style continuity. WEBSITE VIDEO: normally 1 CAPTURE index is the starting frame; interaction scenes may use 2 indexes ordered before then after. PHOTOS: use an empty array.',
          },
          composition: {
            type: 'STRING' as const,
            enum: ['single', 'sequence', 'split', 'triple'],
            description: 'Legacy compatibility field. Use single for current AI-video and photo planning; final motion is generated by the AI video provider.',
          },
          motion: {
            type: 'STRING' as const,
            enum: ['push_in', 'pull_out', 'pan_left', 'pan_right', 'pan_up', 'pan_down', 'static'],
            description: 'Legacy compatibility field. Use static; describe real generated motion in shotDescription instead.',
          },
          focusX: {
            type: 'NUMBER' as const,
            description: 'Legacy compatibility value. Use 0.5 for current AI-video planning.',
          },
          focusY: {
            type: 'NUMBER' as const,
            description: 'Legacy compatibility value. Use 0.5 for current AI-video planning.',
          },
          onScreenCopy: {
            type: 'STRING' as const,
            description: 'MUST be an empty string. Never create extra typography inside generated website footage.',
          },
          transition: {
            type: 'STRING' as const,
            description: 'Narrative handoff intention only. The application does not create screenshot transitions as a substitute for AI-generated motion.',
          },
        },
        required: ['sceneNumber', 'durationSeconds', 'sceneType', 'shotDescription', 'sourceIndices', 'composition', 'motion', 'focusX', 'focusY', 'onScreenCopy', 'transition'],
      },
    },
    voiceoverScript: {
      type: 'STRING' as const,
      nullable: true,
      description: 'MUST be null. No narration is created by the storyboard model.',
    },
  },
  required: ['concept', 'vibe', 'ideas', 'scenes', 'voiceoverScript'],
};

export interface StoryboardInput {
  jobId?: string;
  siteUrl: string;
  pageTitle: string;
  description: string | null;
  screenshotBase64: string | null;
  fullPageScreenshotBase64: string | null;
  referenceCaptures?: Array<{ label: string; base64: string }>;
  mode: string; // video | photos | both | demo | tutorial | buy | tour
  vibeBrief: string;
  targetDurationSeconds: number;
  featuresText?: string | null;
  creativeBrief?: string | null;
  aspectRatio: '16:9' | '9:16' | '1:1';
  outputQuality: '1080p' | '4k';
  frameRate: 24 | 30 | 60;
  variationKey?: string;
}

/** Website-first modes still use real captures for grounding, but every final scene is generated by the selected AI video provider. */
export const SCREEN_STYLE_MODES = ['tutorial', 'buy', 'tour'];

/** Every video-producing mode is now true AI video generation. Photos remain a separate image pipeline. */
export const GENERATIVE_VIDEO_MODES = ['video', 'both', 'demo', 'tutorial', 'buy', 'tour', 'mockup', 'linkedin', 'custom', 'ai-video', 'product-video', 'talking-scene'];
export function isGenerativeVideoMode(mode: string) {
  return GENERATIVE_VIDEO_MODES.includes(mode);
}

const AI_VIDEO_REFERENCE_POLICY = `
AI VIDEO REFERENCE LOCK — REAL WEBSITE, GENERATED MOTION:
- The final deliverable is ONE continuous AI-generated film. The planned scenes are only timeline beats inside that film, grounded by the supplied website screenshots. Do not plan screenshot pans, Ken-Burns moves, code-drawn cursors, slideshow transitions, or separately generated clip resets as the final visual.
- Treat captures as the source of truth for the real website. Preserve visible source-language wording, logos, prices, product identity, colors, controls, navigation labels, and UI structure whenever they are shown. Never translate or redraw the website text. Any NEW on-screen marketing copy requested by the customer must be English only.
- Never invent a product, page, feature, modal, cart state, checkout state, confirmation, price, field value, statistic, claim, or button result that is not supported by the captures.
- A generated cursor/touch action is allowed only on a real visible control. If the resulting state is shown, it must be grounded by another real capture selected in sourceIndices.
- sourceIndices are not editing instructions anymore. They are the strongest real reference states for this scene: normally one capture, or two ordered before/after captures for an interaction. Put states in story order when a before/after interaction is intended.
- onScreenCopy MUST be "" for website-first modes. The website's existing UI text is enough. voiceoverScript MUST be null.

INTERACTION SCENES — REAL ACTION, REAL RESULT:
- Use sceneType="interaction" when the captures support a meaningful real action: select a size/color/variant, add to cart, open cart, open menu/search/filter, start checkout, open a chat/AI assistant, choose a plan, book, sign up, or another actual conversion step visible on this specific site.
- For interaction scenes, sourceIndices should normally contain the real BEFORE state first and the real AFTER state second when both exist. A third reference may support continuity.
- Complete each important action within its planned timeline window and hold the result briefly so the viewer understands what happened. Never let a continuation boundary interrupt the click or state change.
- If there is no captured after-state, do not fabricate it. Either show only the supported action without revealing a result, or choose a different scene.
`;

const AI_VIDEO_PLANNING_SYSTEM = `
AI VIDEO DIRECTING SYSTEM:
- Direct ONE continuous film from start to finish. Planned scenes are timeline beats only; they are never independently generated clips and never reset identity, environment, camera logic, or action at a boundary.
- Think like a commercial director describing progressive motion, interaction, timing, camera behavior, and sound-friendly pacing across one uninterrupted production — not like an FFmpeg editor.
- The first 1.5 seconds must already contain useful brand/site content. No black intro or loading state.
- Each timeline beat should have one clear purpose and a complete visual idea while flowing naturally into the next beat.
- Vary scene subject and motion across the film: different pages, features, products, interaction types, framing, device/context, and camera behavior. The capture stage already removes low-value duplicates, so use that diversity: avoid repeating the same page/reference in adjacent clips unless a before/after interaction requires it.
- For 8-second videos, tell a complete micro-story: hook -> meaningful action/benefit -> clean resolved final moment. Do not cram in unfinished steps.
- For 24-32 seconds, create a strong arc: hook -> distinct middle benefits/actions -> resolution.
- For 48-64 seconds, deliberately spread across genuinely different content. Long videos must feel richer, not slower: no filler, no recycled feature, no identical motion loops.
- Keep real UI text readable and stable while motion happens. Avoid instructions that would encourage warping, morphing, or rewriting the interface.
- Sound is produced later by the AI video provider when enabled, so shotDescription may mention appropriate ambience/UI click rhythm, but do not write spoken dialogue unless the user's brief explicitly asks for it.
`;

const CUSTOM_VIDEO_PLANNING_SYSTEM = `
CUSTOM VIDEO DIRECTING SYSTEM:
- Direct ONE continuous AI-generated film from the customer's idea. Planned scenes are internal timeline beats only, never independently generated clips.
- Direct subject, action, performance, timing, camera behavior, continuity, and sound-friendly pacing as one evolving video — never an FFmpeg effect or moving still.
- The first 1.5 seconds must already contain a useful visual hook. No black intro, loading state, or generic title card.
- Each beat needs one clear purpose and should flow naturally into the next without a reset.
- Keep the same people, products, wardrobe, setting, lighting world, and visual identity consistent throughout unless the written idea explicitly calls for a change.
- Vary shot scale, camera movement, action, and story progression. Longer videos must introduce real progression instead of repeating the same moment more slowly.
- For an 8-second video, deliver a complete micro-story. For longer videos, build hook -> development -> satisfying resolution.
- If the idea includes spoken dialogue, describe natural performance, expressions, mouth movement, gestures and timing. Do not invent dialogue, claims, or on-screen copy that the customer did not request.
`;

const PHOTO_CREATIVE_POLICY = `
PHOTO MODE — REFERENCE-BASED CREATIVE EDITING:
- The supplied reference images/captures are visual REFERENCES and the source of truth for the real product/brand; the final marketing photos MAY be creatively transformed around that real identity.
- Follow the customer's written photo request closely. The user may ask for an ad, campaign visual, product hero, new background, studio setup, lifestyle treatment, seasonal scene, social creative, crop, lighting change, or other marketing edit.
- Preserve recognizable brand/product identity unless the customer explicitly asks to change a specific property.
- You may isolate products from the supplied references and place them into newly created marketing environments when that matches the request.
- Do NOT invent unrelated products, logos, prices, product names, or brand claims.
- Do NOT generate random typography. onScreenCopy MUST be "" for every scene.
- If a website screenshot/UI is one of the references and remains visible in the final image, its existing Arabic/English text must stay faithful to the source; never translate, correct, replace, or redraw that UI text.
- Prefer a strong visual ad with no added text unless the user explicitly asks for marketing copy in their written instructions.
- The four photo scenes should be meaningfully different creative executions, not four near-identical crops.
- voiceoverScript MUST be null.
`;

const BOTH_MODE_POLICY = `
VIDEO + PHOTOS — TWO AI PIPELINES:
- VIDEO OUTPUT: generate one continuous film with the selected AI video model from the real website references. Timeline beats are directing notes only; never fall back to screenshot-only motion or stitched unrelated clips.
- PHOTO OUTPUT: may creatively transform real products/brand into marketing stills according to the user brief.
- In both outputs, never invent unrelated products, prices, claims, features, logos, or random UI text.
- If website UI is visible, preserve its existing Arabic/English wording faithfully.
- onScreenCopy MUST be "". voiceoverScript MUST be null.
`;

const DEMO_CREATIVE_POLICY = `
DEMO MODE — FULL AI CINEMATIC BRAND FILM:
- The result is one continuous true AI-generated video, not independent clips and not AI stills animated by code.
- Captures are grounding references for the real brand, logo, products, colors, and UI. Cinematic surrounding environments, devices, depth, light, reflections, and camera movement are allowed.
- Any website UI shown inside a device/screen must remain faithful to the references. Never invent product names, prices, claims, statistics, discounts, or features.
- Keep one shared visual world and art direction across the entire film, while varying shot scale and motion so the continuous story stays exciting.
- onScreenCopy should normally be "". Never invent marketing copy.
- voiceoverScript MUST be null.
`;

const MOCKUP_CREATIVE_POLICY = `
MOCKUP MODE — DIGITAL PRODUCT / MOTION GRAPHIC SHOWCASE:
- This is a fast, scroll-stopping social-feed style reveal of a digital or physical product's real pages/panels/photos (a template, planner, guide, PDF, or a set of product photos) — the genre sellers use to advertise on TikTok/Instagram/Pinterest.
- Each capture is one real page/panel/photo of the product. Treat each as ground truth: never invent, redraw, retranslate, or restyle its real text, layout, or imagery.
- Generate satisfying AI motion around and between real pages: cards sliding/flipping/stacking into view, a hand or cursor swiping, gentle parallax, a soft zoom settling on a detail — energetic and premium, never a static slideshow.
- The overall presentation may include a light social-media-feed frame (subtle like/comment icon accents, soft neutral background) so it feels native to a Reels/TikTok scroll, but this frame must never cover or distort the real product content.
- Build hook -> quick flip through the strongest real pages/panels -> a satisfying closing reveal. Pacing must feel snappy and current, not corporate.
- onScreenCopy MUST be "" — the real product pages already contain their own real text. voiceoverScript MUST be null.
`;

const CUSTOM_CREATIVE_POLICY = `
CUSTOM MODE — THE CUSTOMER'S OWN VIDEO, NOT A WEBSITE COMMERCIAL:
- This film is directed entirely by the customer's own written idea (CUSTOM USER NOTES below). It is a personal/creative production, not a website or ecommerce promo — it may be a product idea, a lifestyle or narrative scene, a conversation between people, a testimonial, or anything else the customer imagined. Follow the idea closely and specifically. Do NOT default to ecommerce/website structure — no invented "add to cart", checkout, navigation, or UI-review framing — unless the customer's own idea explicitly describes a website or app.
- The final result is ONE continuous film generated by an AI VIDEO model directly from the written idea, optionally guided by customer-uploaded reference images. Timeline beats are planning notes only. Never plan a slideshow of stills, screenshot pans, Ken-Burns moves, code-drawn motion, or separately generated clips as the final visual.
- If a reference image shows a real, recognizable person, product, or place (something the customer actually uploaded), keep that subject recognizable and consistent throughout the film; do not swap their identity or fabricate on-screen text/prices/logos that would misrepresent something real. With no reference image, invent freely to match the written idea.
- If the customer's idea describes people talking, a conversation, narration, or a testimonial, direct real dialogue/performance: natural expressions, gestures, timing and pacing that match spoken lines, as if real words are being said even though the words themselves are written and voiced separately. voiceoverScript MUST still be null in the planning beats (the spoken narration/dialogue for the finished video is generated by a separate step, not written here).
- If the customer's notes leave a creative choice unspecified, make a strong, exciting, professional choice yourself rather than defaulting to something bland or website-like.
- onScreenCopy MUST be "" unless the customer's notes explicitly ask for on-screen text/captions.
`;

const PRODUCT_VIDEO_CREATIVE_POLICY = `
PRODUCT VIDEO MODE — REAL PRODUCT, ONE CONTINUOUS FILM:
- The customer's uploaded product image(s) are the product identity source of truth. Preserve exact shape, proportions, colors, materials, stitching, hardware, logos, packaging and small details.
- The final deliverable is ONE continuous product film. Timeline beats are directing notes only; never plan unrelated product clips or swap the item between beats.
- You may create premium studio, lifestyle, macro-detail and hero environments around the real product when they match the customer's brief, but never redesign, recolor, simplify, replace or invent product details.
- Do not invent prices, product names, claims, readable packaging copy, badges, discounts or random typography.
- Use attached references as identity anchors for continuity throughout the film; sourceIndices may select up to 3 useful product references per timeline beat.
- onScreenCopy MUST be "". voiceoverScript MUST be null.
`;

const ICON_CREATIVE_POLICY = `
WEBSITE ICON MODE — SQUARE BRAND-IDENTITY CONCEPTS:
- Plan four genuinely different 1:1 icon directions grounded in the real captured icon/logo, website purpose, colors, visual language, and customer notes.
- Each result must be one finished icon—not a presentation sheet, browser mockup, screenshot, or collection of alternatives.
- Prioritize a clear silhouette, generous safe padding, small-size readability, and a premium finish suitable for favicon, mobile shortcut, social avatar, and branded video ending.
- Never invent random letters or words. A real existing initial/monogram may be refined only when the captures clearly support it.
- sourceIndices MUST be [] and voiceoverScript MUST be null.
`;


const MODE_MASTER_DIRECTIONS: Record<string, string> = {
  'ai-video': `AI VIDEO — original prompt-driven continuous film.
Treat CUSTOM USER NOTES as the creative brief. Build one coherent film with a strong opening, progressive action, consistent subjects/world, and a resolved ending. Optional uploaded references preserve identity/style only; do not introduce website or ecommerce structure unless the customer explicitly asks for it.`,

  'product-video': `PRODUCT VIDEO — reference-faithful continuous commercial.
Use the uploaded product references as identity ground truth. Plan a premium beginning-to-ending product film with progressive camera/action beats, macro details and a hero resolution while preserving the exact product. Never invent product copy, prices, labels or a different item.`,

  'talking-scene': `TALKING SCENE — performance-first continuous film.
Follow the customer's scenario exactly. Preserve speaker identity, wardrobe, setting and eyelines; plan natural dialogue/performance timing, gestures, reactions and camera blocking as one coherent video. Do not invent unrelated dialogue or scene resets.`,

  video: `PROMO VIDEO — AI-generated premium website commercial.
Inspect what this exact site sells/does and build a real commercial around it. Use different real pages/products/features as references, add purposeful AI-generated motion and believable interaction only where controls/states support it, and make the site feel alive rather than like screenshots. Open with a strong hook, move through distinct benefits or products, include at most one conversion interaction when it helps, and finish on a clean real branded state.`,

  tutorial: `HOW TO USE — AI-generated first-time-user walkthrough.
Teach the real website through believable cursor/touch movement and real captured states. Orient the viewer, then show the most useful actions this specific site supports (browse, search, filter, open item, choose option, use a tool, open chat, etc.). Use before/after captures for actions whenever available. Keep UI readable, complete each important action, and never invent a missing result.`,

  buy: `HOW TO BUY / CONVERT — AI-generated transaction journey.
First infer the website type. For ecommerce, use the real supported purchase path: storefront/category -> product -> option/size/color if captured -> add to cart -> cart -> checkout if captured. For SaaS/service/booking sites, adapt to the actual visible conversion flow such as plan selection, booking, signup, or checkout rather than forcing a shopping cart. Use real before/after states, show natural cursor/touch actions, and never fabricate checkout/payment/success states.`,

  tour: `FEATURE TOUR — AI-generated feature-by-feature showcase.
Discover the strongest real features visible across all captures, including search/filter/navigation, product areas, dashboards, tools, chat/AI assistant, categories, or other site-specific capabilities. Give each scene a different feature purpose and, when a real interaction state exists, show the feature working. Long tours must keep introducing new content and motion instead of repeating the same page.`,

  demo: `CINEMATIC BRAND FILM — fully AI-generated premium product film.
Use the captures as grounding references, then create cinematic motion, dimensional devices, elegant environments, lighting, depth, and premium camera movement. Keep any website UI inside screens faithful to the real references and preserve the actual brand/products. Never invent features, claims, prices, or a different brand.`,

  photos: `PHOTOS — premium marketing image creation from the real captured website.
Use the customer's description as the primary art direction. Plan four distinct campaign images grounded in the real products/brand visible in the captures. Explore useful marketing variations such as product-hero imagery, premium studio/background changes, editorial/lifestyle treatment, social-ad compositions, seasonal campaign treatment, or clean brand visuals — but only when consistent with what the user asked for. Do not add random text. If the user wants the website UI itself shown, keep that UI text faithful to the source instead of recreating it.`,

  icon: `WEBSITE ICON — four premium square brand-mark concepts.
Analyze the captured website, its real icon/logo, business purpose, color system and visual character. Plan four meaningfully different icon concepts that look intentionally designed for this exact brand, remain recognizable at favicon size, and can also work as a mobile shortcut, social avatar and branded video-ending mark.`,

  both: `VIDEO + PHOTOS — true AI-generated commercial plus creative marketing stills.
Plan the video as real AI-generated motion grounded in the website captures, following the PROMO VIDEO logic and never relying on screenshot-only movement. Plan the photos as distinct marketing stills from the same real brand/products.`,

  mockup: `DIGITAL PRODUCT MOCKUP / MOTION GRAPHIC VIDEO — social-feed-style product reveal.
Treat each capture as a real page/panel/photo of a product (digital template, planner, guide, or physical product photos). Build a fast, exciting flip-through: hook on the strongest page first, reveal 3-6 more real pages with satisfying AI-generated motion (slide, flip, stack, gentle zoom), and close on a clean branded or title card if one exists in the captures. This is the exact genre used to advertise digital products/templates on TikTok, Instagram Reels, and Pinterest — energetic, current, scroll-stopping, never corporate or static.`,

  linkedin: `LINKEDIN VIDEO — professional feed story.
Create a credible, business-appropriate video for LinkedIn. Lead with the real problem or result, demonstrate the strongest real website workflow/product proof, and finish on a clean brand state. Prefer restrained motion, readable pacing and 16:9 or square-safe framing. Never invent metrics, customers, testimonials, prices, claims, or capabilities.`,

  custom: `CUSTOM IDEA — the customer's own personal video, AI-directed. This is NOT a website commercial.
Read CUSTOM USER NOTES carefully — that is the actual brief for this film. It may be a product idea, a lifestyle scene, a narrative moment, a conversation between people, a testimonial, or anything else the customer imagined — treat it on its own terms rather than forcing it into a promo/ecommerce shape. Build the strongest possible professional execution of exactly what they described. Reference images are optional visual anchors; without them, plan direct text-to-video scenes. Where the notes are silent on a creative choice, make an exciting, confident decision yourself rather than defaulting to a generic promo or website structure.`,
};

export function stableVariantSeed(value: string | undefined) {
  const text = value || `${Date.now()}`;
  let hash = 2166136261;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash >>> 0) % 9973;
}

function brandNameFrom(input: StoryboardInput) {
  return input.pageTitle.split(/[|\-–—:]/)[0]?.trim() || new URL(input.siteUrl).hostname;
}

function timelineBeatDurations(totalSeconds: number, count: number) {
  const total = Math.max(1, Math.round(totalSeconds));
  const safeCount = Math.max(1, count);
  const base = Math.floor(total / safeCount);
  let remainder = total - base * safeCount;
  return Array.from({ length: safeCount }, () => base + (remainder-- > 0 ? 1 : 0));
}

export function buildFallbackStoryboard(input: StoryboardInput): Storyboard {
  const isIcon = input.mode === 'icon';
  const isPhotos = input.mode === 'photos' || isIcon;
  const isDemo = input.mode === 'demo';
  const isStudioVideo = ['custom', 'ai-video', 'product-video', 'talking-scene'].includes(input.mode);
  const isPromptFirstStudio = ['custom', 'ai-video', 'talking-scene'].includes(input.mode);
  const sceneCount = isPhotos ? 4 : Math.max(1, Math.round(input.targetDurationSeconds / 8));
  const beatDurations = isPhotos ? Array(4).fill(0) : timelineBeatDurations(input.targetDurationSeconds, sceneCount);
  const brandName = brandNameFrom(input);
  const variantSeed = stableVariantSeed(input.variationKey);
  const actualCaptureCount = input.referenceCaptures?.length || Number(Boolean(input.screenshotBase64)) + Number(Boolean(input.fullPageScreenshotBase64));
  const captureCount = Math.max(1, actualCaptureCount);
  const textOnlyStudio = isPromptFirstStudio && actualCaptureCount === 0;
  const featureNames = input.featuresText
    ?.split(/[,\n]/)
    .map((item) => item.trim())
    .filter(Boolean) ?? [];

  const fallbackDirections: Record<string, string[]> = {
    'ai-video': [
      'Open immediately on the strongest visual hook from the customer brief, establishing the subject and world without a title-card delay.',
      'Advance the action in the same world with a meaningfully new camera scale or movement while preserving subject identity.',
      'Develop the idea with a new event, reaction, product detail or narrative progression rather than repeating the opening.',
      'Resolve the customer brief on an intentional final moment that feels complete and stable.',
    ],
    'product-video': [
      'Open with a premium hero reveal of the exact referenced product, preserving every recognizable detail.',
      'Continue into a distinct macro/detail or functional view of the same product with believable commercial camera motion.',
      'Advance into a different premium context or angle while keeping the exact same product identity and materials.',
      'Finish on a clean hero product resolution with no invented text, price or claim.',
    ],
    'talking-scene': [
      'Open directly on the speaker(s) and scenario from the customer brief with natural posture, eyelines and room tone.',
      'Continue the same performance with believable speech timing, gestures and reactions; do not reset wardrobe or setting.',
      'Advance the conversation/action with a useful camera change while keeping identity and continuity stable.',
      'Finish the performance on a natural resolved reaction or line ending instead of cutting mid-sentence.',
    ],
    video: [
      'Generate an immediate premium AI-video reveal from the strongest real homepage state; keep the website text and brand faithful while adding convincing motion.',
      'Generate a different real page/product/feature as a new AI-video beat with purposeful interaction or camera motion supported by that capture.',
      'Generate another distinct website benefit or product with a different motion idea; do not repeat the first page just to fill time.',
      'Finish on a clean real branded state, letting the AI-generated motion resolve fully before the film moves into its ending.',
    ],
    tutorial: [
      'Generate a readable first-time-user orientation on the real homepage with natural cursor/touch movement only on real controls.',
      'Generate the next useful real website step and complete the interaction before cutting.',
      'Use real before/after captures as AI-video states when a genuine feature action is available; never invent the result.',
      'Finish on the clearest genuine outcome/state available and hold it long enough to understand.',
    ],
    buy: [
      'Generate a strong opening from the real storefront/category state and move naturally toward a real product or conversion target.',
      'Generate the real product/service selection step, using cursor/touch interaction only when the visible control supports it.',
      'Generate the next genuine purchase/conversion state from the captures, completing the action before the scene ends.',
      'Finish on the furthest real cart/checkout/booking/signup state available; never invent payment or success.',
    ],
    tour: [
      'Generate an AI-video reveal of the homepage and the first strongest real feature.',
      'Generate a second different real feature with its own purposeful motion or supported interaction.',
      'Generate another distinct tool/category/page so the tour keeps introducing new value instead of repeating content.',
      'Finish on the strongest existing branded interface state with a clean resolved motion.',
    ],
    demo: [
      'Open with a wide reveal of the real logo/brand mark floating in a soft studio environment (marble surface, warm daylight, gentle shadows).',
      'Show a 3D tablet mockup displaying the real captured homepage UI, framed with a glassmorphism accent card naming a real feature/section from the site.',
      'Show a second real UI area (product/category) inside a mockup, with a different camera move, same lighting world as the previous scene.',
      'Finish on a polished branded closing card: the real logo/name and, if present in the capture, the real tagline, on the same studio backdrop.',
    ],
    both: [
      'Generate a premium AI-video opening from the strongest real homepage state.',
      'Generate a different real page/feature/product with a distinct motion idea.',
      'Generate another non-repeating commercial beat grounded in a real capture.',
      'Finish on a clean existing branded state after the AI motion resolves.',
    ],
    photos: [
      'Create a premium hero marketing image based on the strongest real product or brand element in the supplied references and the customer request.',
      'Create a second campaign variation with a meaningfully different composition, background, lighting, or product emphasis while preserving product identity.',
      'Create a social/editorial marketing variation derived from the real referenced product/brand and the customer request; avoid random text.',
      'Create a polished fourth campaign image with a distinct art direction that still clearly belongs to the same real brand and request.',
    ],
    icon: [
      'Create a refined minimal website icon with a clear silhouette, generous safe padding, and excellent favicon-size readability, grounded in the real captured brand.',
      'Create a premium dimensional emblem variation using the site’s real color and shape language without copying unrelated brands or inventing text.',
      'Create a bold geometric brand-mark variation that distills what this website does into one memorable square icon.',
      'Create an elegant editorial icon variation with a distinctive silhouette and a polished finish suitable for mobile, social, and video endings.',
    ],
    mockup: [
      'Open on the strongest real product page/panel with an energetic AI-generated reveal — a card sliding or flipping into view, framed in a light social-feed style.',
      'Flip to a second distinct real page/panel with its own satisfying motion; keep the pace fast and current.',
      'Flip to a third distinct real page/panel, varying the motion style (parallax, stack, gentle zoom) so it never feels repetitive.',
      'Close on the strongest remaining real page/panel or title card with a clean, satisfying final reveal.',
    ],
    linkedin: [
      'Open with a concise professional hook grounded in the strongest real website state.',
      'Show the clearest real workflow, feature, or product proof with readable purposeful motion.',
      'Develop the business value through another distinct real page or supported interaction without inventing claims.',
      'Finish on a clean branded state suitable for a LinkedIn feed post.',
    ],
    custom: [
      'Open with the strongest possible AI-generated hook driven by the customer\u2019s written idea.',
      'Develop the customer\u2019s idea with a distinct second beat that advances the action rather than repeating the opening.',
      'Continue the concept with a genuinely different shot, action, scale, or moment while preserving the same world and subjects.',
      'Resolve the customer\u2019s idea on a clean, satisfying final moment.',
    ],
  };
  const directions = fallbackDirections[input.mode] ?? fallbackDirections.video;

  const scenes = Array.from({ length: sceneCount }, (_, index): StoryboardScene => {
    const isFirst = index === 0;
    const isLast = index === sceneCount - 1;
    const feature = featureNames[index - 1];
    const fallbackDirection = isLast
      ? directions[directions.length - 1]
      : directions[index % Math.max(1, directions.length - 1)];
    const longFormDirection = !isPhotos && sceneCount > directions.length
      ? textOnlyStudio
        ? `${fallbackDirection} Make this beat ${index + 1}/${sceneCount} visually distinct so the longer story keeps advancing instead of repeating filler.`
        : `${fallbackDirection} Make this beat ${index + 1}/${sceneCount} visually distinct and ground it in capture ${((index + variantSeed) % captureCount)} so the long production keeps introducing selected real content instead of repeating filler.`
      : fallbackDirection;
    return {
      sceneNumber: index + 1,
      durationSeconds: beatDurations[index] ?? 8,
      sceneType: isFirst ? 'hook' : isLast ? 'cta' : 'feature',
      shotDescription: feature
        ? (isPhotos
          ? `Use the captured website area that visibly represents “${feature}” as the source reference for a premium marketing image. Follow the customer's photo request and preserve recognizable brand/product identity.`
          : isDemo
            ? `Generate one cinematic frame (device mockup or feature card, same lighting world as the rest of the film) built from the captured area that visibly represents “${feature}”. Use only real brand/product/text elements from that capture — never invent the claim.`
            : `Generate an AI-video scene around the captured website area that visibly represents “${feature}”. Preserve its real UI text/brand and use natural motion or supported interaction without inventing a result.`)
        : longFormDirection,
      sourceIndices: isPhotos || textOnlyStudio
        ? []
        : isStudioVideo
          ? Array.from({ length: Math.min(3, actualCaptureCount) }, (_, offset) => (index + variantSeed + offset) % actualCaptureCount)
          : [((index + variantSeed) % captureCount)],
      composition: 'single',
      motion: 'static',
      focusX: isPhotos ? 0.5 : 0.32 + ((variantSeed + index * 17) % 37) / 100,
      focusY: isPhotos ? 0.5 : isFirst ? 0.22 + (variantSeed % 10) / 100 : isLast ? 0.18 + (variantSeed % 14) / 100 : 0.34 + ((variantSeed + index * 11) % 34) / 100,
      onScreenCopy: '',
      transition: isLast ? '' : 'Continue naturally into the next timeline beat of the same film without a visual or identity reset.',
    };
  });

  return {
    concept: isIcon
      ? `${brandName} distilled into four premium square icon concepts grounded in its real website identity.`
      : isPhotos
        ? `${brandName} turned into a premium marketing photo set using the supplied real references as product/brand ground truth.`
      : isStudioVideo
        ? `A professionally directed continuous AI video generated from the customer's ${input.mode === 'product-video' ? 'real product references and product-film direction' : 'written idea'}${actualCaptureCount ? ' and reference images' : ''}.`
      : isDemo
        ? `${brandName} presented as a generative cinematic brand film — AI-composited device mockups and feature cards grounded in its real logo, products, and captured brand content.`
        : `${brandName} presented as a true AI-generated website film grounded in its real captured pages, products, UI and brand.`,
    vibe: input.vibeBrief,
    ideas: isIcon
      ? [
          'Minimal favicon-first symbol with strong small-size clarity',
          'Premium dimensional app-icon treatment using the real brand palette',
          'Distinctive geometric or editorial mark suited to the website’s audience',
        ]
      : isPhotos
        ? [
          'Premium product-hero campaign based on the real captured product imagery',
          'Editorial/social marketing variation with a new art-directed environment',
          'Clean commercial campaign set with distinct compositions and no random typography',
        ]
      : isStudioVideo
        ? input.mode === 'product-video'
          ? [
              'Premium hero-to-detail product film preserving the exact referenced item',
              'Editorial product story with macro details and a strong final hero angle',
              'Lifestyle/studio product film with consistent materials, shape, and brand identity',
            ]
          : input.mode === 'talking-scene'
            ? [
                'Natural performance-first take with clean conversational camera blocking',
                'A warmer story-led take with stronger reactions and human pacing',
                'A polished commercial dialogue take with subtle camera movement and a resolved ending',
              ]
            : [
                'A cinematic interpretation focused on one clear action and atmosphere',
                'A story-led version with stronger character or subject progression',
                'A visually bold variation with different framing, pacing, and camera language',
              ]
      : isDemo
        ? [
            'Device-mockup-led brand film with glassmorphism feature cards',
            'Lifestyle/studio product-hero film ending on a branded closing card',
            'Responsive-design showcase moving from desktop to tablet to phone mockups',
          ]
        : [
          'AI-generated website commercial with real interaction states and faithful UI',
          'Feature-led generated motion using different real captured pages',
          'Conversion journey with real before/after states and no fabricated outcomes',
        ],
    scenes,
    voiceoverScript: null,
    targetDurationSeconds: isPhotos ? 0 : Math.max(8, Math.round(input.targetDurationSeconds)),
    creativeBrief: input.creativeBrief?.trim() || undefined,
    aspectRatio: input.aspectRatio,
    outputQuality: input.outputQuality,
    frameRate: input.frameRate,
    variantSeed,
  };
}

export function storyboardModelName() {
  return process.env.GEMINI_STORYBOARD_MODEL ?? 'gemini-3.6-flash';
}

type PlannerPart = { inlineData: { mimeType: string; data: string } } | { text: string };

export interface PlannerPrompt {
  prompt: string;
  captureParts: PlannerPart[];
  captureCount: number;
  sceneCount: number;
  variantSeed: number;
  isPhotos: boolean;
  isDemo: boolean;
}

/**
 * Deterministic prompt assembly for the storyboard planner. Exported so the
 * automated tests can prove each feature/mode actually delivers its own master
 * direction plus the correct capture-preservation policy to the model.
 */
export function buildStoryboardPrompt(input: StoryboardInput): PlannerPrompt {
  const {
    siteUrl, pageTitle, description,
    screenshotBase64, fullPageScreenshotBase64, referenceCaptures,
    mode, vibeBrief, targetDurationSeconds, featuresText,
    creativeBrief, aspectRatio, outputQuality, frameRate, variationKey,
  } = input;

  const captureParts: PlannerPart[] = [];
  const labeledCaptures = (referenceCaptures ?? []).filter((capture) => capture.base64).slice(0, 30);
  if (labeledCaptures.length > 0) {
    labeledCaptures.forEach((capture, index) => {
      captureParts.push({ text: `CAPTURE ${index}: ${capture.label}` });
      captureParts.push({ inlineData: { mimeType: 'image/jpeg', data: capture.base64 } });
    });
  } else {
    if (screenshotBase64) {
      captureParts.push({ text: 'CAPTURE 0: Homepage viewport screenshot' });
      captureParts.push({ inlineData: { mimeType: 'image/jpeg', data: screenshotBase64 } });
    }
    if (fullPageScreenshotBase64) {
      captureParts.push({ text: `CAPTURE ${screenshotBase64 ? 1 : 0}: Homepage full-page screenshot` });
      captureParts.push({ inlineData: { mimeType: 'image/jpeg', data: fullPageScreenshotBase64 } });
    }
  }
  const captureCount = labeledCaptures.length || Number(Boolean(screenshotBase64)) + Number(Boolean(fullPageScreenshotBase64));

  const isIcon = mode === 'icon';
  const isPhotos = mode === 'photos' || isIcon;
  const isDemo = mode === 'demo';
  const isCustom = mode === 'custom';
  const isStudioVideo = ['custom', 'ai-video', 'product-video', 'talking-scene'].includes(mode);
  const isPromptFirstStudio = ['custom', 'ai-video', 'talking-scene'].includes(mode);
  const isProductVideo = mode === 'product-video';
  const isUploadProject = siteUrl.startsWith('upload://');
  const sceneCount = isPhotos ? 4 : Math.max(1, Math.round(targetDurationSeconds / 8));
  const brandName = brandNameFrom(input);
  const modeDirection = MODE_MASTER_DIRECTIONS[mode] ?? MODE_MASTER_DIRECTIONS.video;
  const variantSeed = stableVariantSeed(variationKey);

  const featuresBlock = featuresText?.trim()
    ? `OWNER-REQUESTED FEATURES: ${featuresText.trim()}\nUse them only when they are visibly present in the captured website. Never fabricate a missing feature.`
    : mode === 'tour'
      ? 'No features were specified. Detect the strongest features that are actually visible in the screenshots.'
      : '';

  const structureBlock = isIcon
    ? `Create exactly 4 website-icon scenes. Each scene should be a distinct square brand-mark direction grounded in the captured website/icon references and the customer's request.`
    : isPhotos
      ? `Create exactly 4 marketing-photo scenes. Each scene should be a distinct image-generation/editing direction grounded in the captured website references and the customer's request.`
    : isDemo
      ? `Create exactly ${sceneCount} timeline beats spanning ONE continuous ${targetDurationSeconds}s AI-generated film. These beats are planning checkpoints only, NOT independent clips. Keep one consistent cinematic world while progressing naturally through the full film.`
    : isStudioVideo
      ? `Create exactly ${sceneCount} timeline beats spanning ONE continuous ${targetDurationSeconds}s AI-generated film. These beats guide one evolving video, not separate generated clips. ${isProductVideo ? 'Use the uploaded product references as exact identity anchors throughout.' : captureCount ? 'sourceIndices may choose up to 3 uploaded reference images as identity/product/place/style references for the continuous film.' : 'No reference image exists: use sourceIndices=[] and plan direct text-to-video.'}`
      : `Create exactly ${sceneCount} timeline beats spanning ONE continuous ${targetDurationSeconds}s AI-generated film. The beats are a directing timeline only; the renderer generates one continuous video and never concatenates independent scene clips. sourceIndices identify the strongest real screenshot references for the film.`;
  const coverageBlock = !isPhotos && captureCount > 1
    ? sceneCount >= captureCount - 1
      ? `MEDIA COVERAGE: The duration is long enough to cover the selected media. Progress through the strongest references as distinct moments inside the same continuous film. If a WEBSITE ICON / LOGO capture is attached, reserve it for brand continuity or the closing beat.`
      : `MEDIA FOCUS: There are ${captureCount} references but only ${sceneCount} timeline beats. Choose the strongest ${sceneCount} references for the customer’s mode and brief; do not force unrelated references into one moment.`
    : '';

  const capturePolicy = mode === 'icon'
    ? ICON_CREATIVE_POLICY
    : mode === 'photos'
      ? PHOTO_CREATIVE_POLICY
    : mode === 'both'
      ? `${AI_VIDEO_REFERENCE_POLICY}\n${BOTH_MODE_POLICY}`
      : isDemo
        ? `${AI_VIDEO_REFERENCE_POLICY}\n${DEMO_CREATIVE_POLICY}`
        : mode === 'mockup'
          ? `${AI_VIDEO_REFERENCE_POLICY}\n${MOCKUP_CREATIVE_POLICY}`
          : isProductVideo
          ? PRODUCT_VIDEO_CREATIVE_POLICY
          : isPromptFirstStudio
            // Studio idea/talking-scene modes deliberately do NOT inherit the
            // website/ecommerce policy. Their customer prompt is the creative brief.
            ? CUSTOM_CREATIVE_POLICY
            : AI_VIDEO_REFERENCE_POLICY;

  const prompt = `You are an elite commercial director and storyboard planner. ${isStudioVideo ? 'Direct this studio production as its own film; a website is not involved.' : isPhotos && isUploadProject ? 'Art-direct this reference-based image production; a website is not involved.' : 'Ground every decision in the real browser captures and obey the selected mode\'s preservation rules.'}

PROJECT
${isStudioVideo ? `PROJECT TYPE: ${isProductVideo ? 'Product video' : mode === 'talking-scene' ? 'Talking scene' : 'Independent AI video'}
WORKING TITLE: ${pageTitle}` : isPhotos && isUploadProject ? `PROJECT TYPE: Product / reference photo campaign
WORKING TITLE: ${pageTitle}` : `SITE: ${siteUrl}
BRAND: ${brandName}
PAGE TITLE: ${pageTitle}`}
DESCRIPTION: ${description ?? 'not available'}
MODE: ${mode}
REQUESTED MOOD: ${vibeBrief}
CUSTOM USER NOTES: ${creativeBrief?.trim() || 'No extra notes — use the strongest professional direction for this mode.'}
DELIVERY: ${aspectRatio}, ${outputQuality === '4k' ? '4K' : '1080p'}, ${frameRate} FPS
CREATIVE VARIATION ID: ${variantSeed}
This is a fresh generation attempt. ${isStudioVideo ? 'Use the variation ID to choose a fresh interpretation, camera language, performance/action and rhythm while preserving the requested subject/product identity.' : 'Use the variation ID to deliberately choose a different real-content sequence, interaction mix, camera behavior, motion rhythm, and reference-state selection while preserving website fidelity.'}
${featuresBlock ? `\n${featuresBlock}\n` : ''}

MODE-SPECIFIC MASTER DIRECTION
${modeDirection}

${capturePolicy}

${isPhotos ? '' : isStudioVideo ? CUSTOM_VIDEO_PLANNING_SYSTEM : AI_VIDEO_PLANNING_SYSTEM}

CAPTURE CONTEXT
${isStudioVideo
  ? captureCount > 0
    ? `Attached are ${captureCount} customer reference image${captureCount === 1 ? '' : 's'}. CAPTURE indexes are zero-based. ${isProductVideo ? 'They are exact product identity references; preserve the same product throughout the continuous film.' : 'sourceIndices may select up to 3 as identity/product/place/style anchors; they are not separate scenes or literal reset frames.'} The written customer direction remains the creative brief.`
    : isProductVideo
      ? 'No product reference is attached. Do not invent a substitute product; this production should fail validation before rendering.'
      : 'No reference image is attached or required. This is direct text-to-video: follow the written idea, create sourceIndices=[] for every timeline beat, and do not introduce website, ecommerce, or screenshot language.'
  : isPhotos && isUploadProject
    ? captureCount > 0
      ? `Attached are ${captureCount} real product/reference image${captureCount === 1 ? '' : 's'}. Treat them as identity ground truth for the photo campaign. Study all references; photos use sourceIndices=[] because the image generator receives the references directly.`
      : 'No usable product/reference image is attached. Do not invent a substitute product.'
  : captureCount > 0
  ? `Attached are ${captureCount} labeled real website screenshots that were prefiltered for page importance and duplicate removal. CAPTURE indexes are zero-based and sourceIndices MUST refer only to those indexes. Study every capture and prefer different useful references across the story. For video modes, sourceIndices select the real grounding state(s) for the AI video model; for an interaction, place the real before-state first and the real after-state second when available. The separate smooth-scroll recording is not used as a substitute for AI video generation.`
  : 'No screenshot is attached to planning. Stay conservative, follow the customer brief, and do not invent brand/product facts.'}

STRUCTURE
${structureBlock}
${coverageBlock}

TEXT LANGUAGE POLICY
- Generated on-screen typography is never automatic. Keep onScreenCopy empty unless the customer's idea explicitly requires visible marketing text.
- If visible generated copy is explicitly required, translate its intended meaning into short, natural, correctly spelled ENGLISH for the video direction regardless of the language of the customer prompt or source website. Brand names and proper names remain unchanged.
- Existing website/reference text is source imagery: never translate, retype, redraw, or "correct" it. For dense non-English UI, plan wider/stable framing rather than asking the video model to recreate the lettering.
- This policy is only for visible generated text; spoken dialogue/narration follows the selected audio/language direction.

OUTPUT REQUIREMENTS
- concept: one sharp sentence describing the production concept for this selected mode.
- ideas: 3-5 alternate approaches that obey the selected mode policy and customer request.
- scenes: ${isStudioVideo ? 'for VIDEO modes these are timeline beats inside one continuous film; each shotDescription says what should happen during that part of the film while preserving continuity before and after it.' : 'for VIDEO modes these are timeline beats inside one continuous film: describe the real page/state or subject, the motion/action, camera behavior, and how that beat flows naturally into the next. For PHOTOS, each shotDescription remains a distinct marketing-image direction.'}
- sourceIndices: ${isStudioVideo ? (captureCount ? 'use 0-3 valid CAPTURE indexes as identity/style/product references when they help preserve continuity. Do not treat them as separate clips or reset frames.' : 'always use [] because this is direct text-to-video with no reference images.') : 'VIDEO normally uses 1 valid CAPTURE index as the AI-video starting frame and should rotate through distinct useful references instead of repeatedly using the same page; interaction scenes use 2 valid indexes in before/after order. PHOTOS uses [].'}
- composition/motion/focus fields are retained only for backwards-compatible storyboard shape; the AI video renderer does not use them to manufacture motion. Use composition="single", motion="static", focusX=0.5, focusY=0.5 unless a legacy client needs otherwise.
- onScreenCopy: "" for every scene. ${isStudioVideo ? 'Do not add generated text unless the customer explicitly requested on-screen copy. If they did, direct only short correctly spelled ENGLISH copy; keep brand/proper names unchanged.' : 'Never invent website/campaign typography. Existing source-language website text stays in the reference and is never translated or redrawn.'}
- voiceoverScript: ALWAYS null.
- transition: describe the natural narrative handoff into the next timeline beat of the SAME continuous video; never describe a reset or a separately generated clip.

${isStudioVideo ? 'This studio production is independent from the website pipeline. Follow the customer\'s direction and its reference images only.' : 'For every website-video mode, preserve real website text and state truth while allowing the AI video model to generate the motion itself. For photos, creative visual generation remains governed by the photo policy.'}`;

  return { prompt, captureParts, captureCount, sceneCount, variantSeed, isPhotos, isDemo };
}

export interface StoryboardResult {
  storyboard: Storyboard;
  /**
   * The exact reason the Gemini planner could not be used, when a fallback
   * plan had to be substituted. Null when Gemini produced the plan itself.
   * Callers are expected to surface this to the user verbatim (it is our own
   * caught Error#message, never a raw stack trace or secret).
   */
  aiError: string | null;
}

function describeStoryboardError(err: unknown, model: string): string {
  const raw = err instanceof Error ? err.message : String(err);
  // Normalize the most common Gemini failure shapes into something short and
  // exact, without inventing detail we don't actually have.
  return `Gemini storyboard model "${model}" failed: ${raw}`;
}

export async function generateStoryboard(input: StoryboardInput): Promise<StoryboardResult> {
  const { mode, creativeBrief, aspectRatio, outputQuality, frameRate } = input;
  const { prompt, captureParts, captureCount, sceneCount, variantSeed, isPhotos, isDemo } = buildStoryboardPrompt(input);
  const isStudioVideo = ['custom', 'ai-video', 'product-video', 'talking-scene'].includes(mode);
  const textOnlyStudio = ['custom', 'ai-video', 'talking-scene'].includes(mode) && captureCount === 0;
  const model = storyboardModelName();
  console.info(`[storyboard] model=${model} mode=${mode} variation=${variantSeed} captures=${captureCount} scenes=${sceneCount}`);

  try {
    const client = getClient();
    const response = await runQueuedProviderCall({
      kind: 'storyboard',
      model,
      operation: 'storyboard_planning',
      jobId: input.jobId,
      task: () => client.models.generateContent({
        model,
        contents: [{ role: 'user', parts: [...captureParts, { text: prompt }] }],
        config: {
          responseMimeType: 'application/json',
          responseSchema: STORYBOARD_SCHEMA as Parameters<typeof client.models.generateContent>[0]['config'] extends { responseSchema?: infer T } ? T : never,
          temperature: 0.72,
        },
      }),
    });

    if (input.jobId) await recordGeminiTextUsage(input.jobId, model, 'storyboard_planning', response.usageMetadata);

    const text = response.text ?? '';
    const parsed = JSON.parse(text) as Storyboard;
    parsed.targetDurationSeconds = isPhotos ? 0 : Math.max(8, Math.round(input.targetDurationSeconds));
    const parsedBeatDurations = isPhotos ? Array(sceneCount).fill(0) : timelineBeatDurations(parsed.targetDurationSeconds, sceneCount);
    parsed.creativeBrief = creativeBrief?.trim() || undefined;
    parsed.aspectRatio = aspectRatio;
    parsed.outputQuality = outputQuality;
    parsed.frameRate = frameRate;
    parsed.variantSeed = variantSeed;
    parsed.voiceoverScript = null;
    parsed.scenes = (parsed.scenes ?? []).slice(0, sceneCount).map((scene, index) => {
      // Compatibility fields remain in the stored storyboard, but motion itself
      // is generated by the AI video provider rather than manufactured here.
      return {
        ...scene,
        sceneNumber: index + 1,
        durationSeconds: parsedBeatDurations[index] ?? 8,
        sourceIndices: isPhotos || textOnlyStudio
          ? []
          : (scene.sourceIndices ?? [index % Math.max(1, captureCount)])
              .filter((value) => Number.isInteger(value) && value >= 0 && value < Math.max(1, captureCount))
              .filter((value, position, values) => values.indexOf(value) === position)
              .slice(0, isStudioVideo ? 3 : scene.sceneType === 'interaction' ? 2 : 1),
        composition: 'single',
        motion: 'static' as StoryboardScene['motion'],
        focusX: Math.max(0, Math.min(1, Number(scene.focusX ?? 0.5))),
        focusY: Math.max(0, Math.min(1, Number(scene.focusY ?? 0.5))),
        onScreenCopy: '',
        transition: index === sceneCount - 1 ? '' : scene.transition,
      };
    });
    if (!isPhotos && !textOnlyStudio) {
      parsed.scenes = parsed.scenes.map((scene, index) => ({
        ...scene,
        sourceIndices: scene.sourceIndices?.length
          ? scene.sourceIndices
          : isStudioVideo
            ? Array.from({ length: Math.min(3, captureCount) }, (_, offset) => (index + variantSeed + offset) % captureCount)
            : [index % Math.max(1, captureCount)],
      }));

      // Enforce reference variety after AI planning. Keep a valid AI choice
      // when it is distinct, but do not let ordinary scenes repeatedly use
      // the first screenshot while other real references are still unused.
      if (!isStudioVideo && captureCount > 1) {
        const usedPrimary = new Set<number>();
        parsed.scenes = parsed.scenes.map((scene, index) => {
          if (scene.sceneType === 'interaction' && (scene.sourceIndices?.length ?? 0) > 1) {
            const primary = scene.sourceIndices![0];
            usedPrimary.add(primary);
            return scene;
          }
          let primary = scene.sourceIndices?.[0] ?? -1;
          if (primary < 0 || usedPrimary.has(primary)) {
            const unused = Array.from({ length: captureCount }, (_, offset) => (variantSeed + index + offset) % captureCount)
              .find((candidate) => !usedPrimary.has(candidate));
            if (unused !== undefined) primary = unused;
          }
          if (primary >= 0) usedPrimary.add(primary);
          return { ...scene, sourceIndices: primary >= 0 ? [primary] : [] };
        });
      }
    }
    if (parsed.scenes.length !== sceneCount) {
      const aiError = `Gemini storyboard model "${model}" returned ${parsed.scenes.length}/${sceneCount} scenes (an incomplete plan), so the built-in backup plan was used instead.`;
      console.warn(`[storyboard] ${aiError}`);
      return { storyboard: buildFallbackStoryboard(input), aiError };
    }
    return { storyboard: parsed, aiError: null };
  } catch (err) {
    const aiError = describeStoryboardError(err, model);
    console.error(`[storyboard] ${aiError}`);
    return { storyboard: buildFallbackStoryboard(input), aiError };
  }
}
