import type { StoryboardScene } from './gemini.js';

export const VIDEO_MASTER_PROMPTS: Record<string, string> = {
  video: `PROMO VIDEO — AI-GENERATED WEBSITE COMMERCIAL
Create a real AI-generated commercial, not a slideshow and not a screen recording. Study the supplied website captures and identify what the website actually sells or does. Use the real UI, products, brand, colors, navigation, and visible content as the source of truth. Animate the website naturally with purposeful cursor/touch interaction only when an actual visible control supports it. Build a strong advertising arc: immediate hook, different real benefits/pages/products, satisfying interaction moments, and a clean branded ending. Do not repeat the same page or movement just to fill time.`,

  tutorial: `HOW TO USE — AI-GENERATED GUIDED WALKTHROUGH
Create a clear, believable AI-generated walkthrough of this exact website. Infer the useful first-time-user journey from the captures. Show the cursor or touch indicator moving naturally to real visible controls, clicking them, and then arriving at the next real captured state. Use readable pacing around important UI, but keep the video alive and polished. Never invent a feature, button result, page, menu, form state, or success state that is not grounded by the supplied captures.`,

  buy: `HOW TO BUY / CONVERT — AI-GENERATED TRANSACTION JOURNEY
First determine the website type from the captures. If it is ecommerce, create the real purchase journey that the available states support: browse/category → real product → real option/size/color when visible → add to cart → cart → checkout when captured. If it is a service/SaaS/booking website, adapt the same conversion logic to the real flow that is visible (for example plan selection, booking, signup, or checkout) instead of forcing an ecommerce cart. Show believable cursor/touch movement and complete each important action before cutting. Never fabricate a checkout, payment, confirmation, cart result, price, field value, or button that is not supported by a capture.`,

  tour: `FEATURE TOUR — AI-GENERATED FEATURE SHOWCASE
Inspect all captures and discover the strongest real features, tools, pages, sections, categories, search/filter controls, chat/AI assistant, dashboards, product areas, or navigation patterns that actually exist. Give each scene one distinct feature purpose. Show the feature working when real before/after states support it; otherwise animate the existing interface cinematically without inventing a result. Long tours must keep changing subject, scale, interaction, and page so they never become repetitive.`,

  demo: `CINEMATIC BRAND FILM — FULLY AI-GENERATED
Create a premium AI-generated brand/product film grounded in the real website references. The surrounding world may be cinematic (studio, device, elegant environment, dimensional camera movement), but any website UI shown on a screen must remain faithful to the supplied captures. Preserve the real logo, product identity, colors, prices, and visible interface wording. Do not invent features, claims, statistics, discounts, review counts, or a different brand. Make every scene feel part of one consistent directed film, not unrelated AI shots.`,

  both: `VIDEO + PHOTOS — AI-GENERATED WEBSITE COMMERCIAL
For the VIDEO portion, follow the PROMO VIDEO rules: every video scene must be generated by the AI video model from the real website references, never constructed from screenshot pans/zooms/transitions. Build a varied commercial arc grounded in the real site. The separate photo pipeline may create marketing stills from the same brand references.`,

  mockup: `DIGITAL PRODUCT MOCKUP — AI-GENERATED MOTION GRAPHIC REVEAL
Create the fast, scroll-stopping style used to advertise digital products (templates, planners, guides, PDFs) or physical products on TikTok, Instagram Reels, and Pinterest. Each reference is a real page/panel/photo of the product — treat it as ground truth, never redraw or retranslate its real text or layout. Generate energetic AI motion around and between real pages: cards sliding, flipping, or stacking into view, a natural swipe, gentle parallax, a soft zoom settling on a real detail. A light social-feed frame (subtle like/comment icon accents, soft neutral background) is welcome but must never cover or distort the real product content. Build hook → quick flip through the strongest real pages → satisfying closing reveal. Snappy, current, premium — never a static slideshow, never corporate.`,

  linkedin: `LINKEDIN VIDEO — PROFESSIONAL AI-GENERATED FEED STORY
Create a polished, credible video for the LinkedIn feed using the real website as evidence. Open with a concise problem/result hook, demonstrate the strongest real workflow, feature or product proof, and resolve on a clean branded state. Use restrained professional motion, readable pacing and business-appropriate sound design. Keep the composition safe for desktop and mobile LinkedIn feeds. Never invent metrics, customers, testimonials, prices, claims, endorsements or capabilities that are not supported by the supplied captures.`,

  custom: `CUSTOM IDEA — AI-DIRECTED FROM THE USER'S OWN CONCEPT
The user's own written brief is the actual creative direction for this scene, not a generic template — follow it closely and specifically. The supplied captures/photos remain ground truth: never invent products, text, prices, logos, or claims not visibly supported by them, and every scene is still true AI-generated video, never code-driven motion. Where the user's brief leaves a creative choice open, make a strong, exciting, professional choice rather than defaulting to something bland.`,
};

export const GLOBAL_AI_VIDEO_RULES = `
NON-NEGOTIABLE WEBSITE FIDELITY RULES
- The supplied screenshots are the visual source of truth. Use them as starting/end/reference frames for AI video generation.
- Never rewrite, translate, correct, relabel, respell, replace, or hallucinate visible website text. Preserve Arabic and English wording, logos, prices, product names, buttons, labels, and brand marks exactly as shown whenever they are visible.
- Never invent a product, page, modal, control, cart state, checkout state, payment state, confirmation, feature, claim, review, statistic, discount, field value, or navigation item that is not supported by the supplied captures.
- You MAY generate natural motion, cursor movement, taps/clicks, scrolling-like movement, dimensional camera movement, UI transitions, reflections, depth, lighting, or cinematic surroundings, but the action must remain grounded in real controls/states from the references.
- For an interaction, the action and its result must both be supported. If a "before" capture exists but no "after" state exists, show the action only if the result is not displayed; otherwise omit the action rather than inventing what happens.
- Never create random captions, subtitles, fake CTA cards, fake browser text, or generated marketing copy unless the user's own brief explicitly asks for separate non-UI copy. Even then, keep it outside the website UI and never cover important interface content.
- Avoid morphing or warping text, logos, faces, products, or UI geometry. Keep interface planes stable and readable while motion occurs.
- Do not turn the website into a generic stock video. The website and its real content must stay central.

AI VIDEO, NOT CODE-GENERATED MOTION
- Every scene must be a real video clip generated by the selected AI video provider.
- Do not describe Ken Burns pans, deterministic crop animations, code-drawn cursors, slideshow transitions, or screenshot-only editing as the scene itself.
- The application may technically join completed AI clips, normalize resolution, crop a delivery format, or mix/strip audio, but it must not manufacture the visual action in place of AI video generation.

PACING AND COMPLETENESS
- The opening must have useful visual information immediately; no black intro, loading screen, or dead air.
- Never cut in the middle of a meaningful click, selection, add-to-cart action, page transition, checkout step, or other important interaction. Complete the beat and leave a readable moment after the result.
- Short videos must tell a complete micro-story: hook → one or two meaningful actions/benefits → clean resolution. Fewer complete beats are better than many unfinished beats.
- Long videos must continuously introduce genuinely different pages, products, features, interactions, shot scales, or environments. Do not stretch duration by repeating the same screenshot, movement, or feature.
- Keep important text readable long enough to understand without freezing the whole scene.

AUDIO
- When sound is enabled, generate scene-appropriate audio as part of the AI video whenever the provider supports native audio: tasteful music/ambience plus subtle UI clicks/taps/transition sounds when appropriate.
- Avoid loud or distracting effects. Do not generate random spoken dialogue. If a separate narration track is requested/provided, leave enough space in the mix for it.
- For tutorial/buy flows, prioritize clean UI click/tap feedback and a light supporting bed. For promo/demo, use more cinematic rhythmic sound design. For feature tours, use polished modern tech/product sound design.
- When sound is disabled, visual timing must still work perfectly without relying on audio cues.
`;

const RUNTIME_AI_VIDEO_RULES = `
EXECUTION RULES
- Generate a REAL moving AI-video clip from the supplied website references; never simulate the scene with a moving still/slideshow.
- The captures are truth. Preserve visible Arabic/English UI text, logo, product identity, prices, buttons and layout; never invent or rewrite UI, products, claims or states.
- A cursor/touch may act only on a real visible control. Show an outcome only when a supplied reference proves that outcome. For before/after references, move naturally from the first real state to the last and finish the action before the clip ends.
- Keep text/UI stable and readable; avoid morphing, warped letters, duplicate controls, fake captions or random marketing text.
- Short films need a complete beat, not an unfinished click. Long films must vary pages/features/actions and never repeat filler.
- If sound is enabled, use tasteful mode-appropriate music/ambience and subtle UI effects; no random dialogue.
`;

function modePrompt(mode: string) {
  return VIDEO_MASTER_PROMPTS[mode] ?? VIDEO_MASTER_PROMPTS.video;
}

function compactText(value: string | undefined | null, max: number) {
  const text = (value ?? '').replace(/\s+/g, ' ').trim();
  return text.length <= max ? text : `${text.slice(0, Math.max(0, max - 1)).trimEnd()}…`;
}

export interface VideoScenePromptInput {
  mode: string;
  siteTitle: string;
  concept: string;
  vibe: string;
  scene: StoryboardScene;
  sceneIndex: number;
  totalScenes: number;
  targetDurationSeconds: number;
  creativeBrief?: string;
  nativeAudio: boolean;
  musicOnly?: boolean;
  referenceLabels?: string[];
  variantSeed?: number;
  aspectRatio?: '16:9' | '9:16' | '1:1';
  previousSceneSummary?: string;
  nextSceneSummary?: string;
}

export function buildAiVideoScenePrompt(input: VideoScenePromptInput) {
  const {
    mode, siteTitle, concept, vibe, scene, sceneIndex, totalScenes,
    targetDurationSeconds, creativeBrief, nativeAudio, musicOnly, referenceLabels, variantSeed, aspectRatio, previousSceneSummary, nextSceneSummary,
  } = input;
  const position = sceneIndex === 0 ? 'opening scene' : sceneIndex === totalScenes - 1 ? 'closing scene' : `middle scene ${sceneIndex + 1}`;
  const refs = (referenceLabels ?? []).filter(Boolean).map((value) => compactText(value, 80));
  const safeSiteTitle = compactText(siteTitle, 80);
  const safeConcept = compactText(concept, 140);
  const safeVibe = compactText(vibe, 80);
  const safeBrief = compactText(creativeBrief, 280);
  const safeScene = compactText(scene.shotDescription, 500);
  const safePrevious = compactText(previousSceneSummary, 140);
  const safeNext = compactText(nextSceneSummary, 140);

  return `${modePrompt(mode)}\n\n${RUNTIME_AI_VIDEO_RULES}\n
PROJECT
Brand/site: ${safeSiteTitle}
Overall concept: ${safeConcept}
Mood: ${safeVibe}
Total film length: about ${targetDurationSeconds}s across ${totalScenes} AI-generated clips
This clip: ${position}, scene ${sceneIndex + 1}/${totalScenes}, exactly ${scene.durationSeconds || 8}s
Scene purpose: ${scene.sceneType}
Creative variation seed: ${variantSeed ?? 0}
User direction: ${safeBrief || 'No additional user direction.'}
Reference states used for this clip: ${refs.length ? refs.join(' | ') : 'real website screenshots supplied as visual references'}
Delivery framing: ${aspectRatio ?? '16:9'}${aspectRatio === '1:1' ? ' — keep the important website UI, cursor action and products inside the central square-safe area because mastering performs only a technical center crop.' : ''}

SCENE DIRECTION
${safeScene}

FILM CONTINUITY
Previous beat: ${safePrevious || 'This is the opening beat.'}
Next beat: ${safeNext || 'This is the closing beat.'}
Resolve this scene cleanly so the edit can cut to the next AI-generated clip without interrupting an action.

INTERACTION EXECUTION
${scene.sceneType === 'interaction'
  ? `This is an interaction scene. Show a natural cursor/touch movement reaching the actual visible control, performing the real action, and—only when the supplied references include the resulting state—complete the transition into that exact real state. Hold the result long enough to read it. Do not create a code-style pulse marker or fake overlay.`
  : `If interaction improves this scene, it must still use a real visible control and a real supported outcome. Otherwise focus on convincing AI-generated motion of the real website content.`}

CONTINUITY
Make this clip materially different from neighboring clips in subject and motion, while preserving the same real brand. ${totalScenes >= 6 ? 'Because this is a long film, do not reuse the same page/feature unless the purpose is clearly different.' : 'Because this is a short/medium film, every second must advance the idea.'}

AUDIO DIRECTION
${nativeAudio
  ? musicOnly
    ? 'MUSIC ONLY. Generate tasteful instrumental music, ambience, and subtle UI/transition sound design matching the mood. Absolutely no talking, narration, dialogue, vocals, sung words, whispers, or human speech in any language.'
    : 'Generate native audio appropriate to this mode and scene. Keep one consistent sonic identity matching the overall mood so neighboring AI clips feel like the same film. Use tasteful music/ambience/UI sound design and leave space for the separate narration track; do not generate dialogue inside the scene.'
  : 'The delivered master is silent. Do not make the visual story depend on sound.'}

CRITICAL FINAL CHECK
Before generating, verify: all visible website words remain faithful to the reference; no invented UI/state/price/claim; the meaningful action finishes before the clip ends; this is real generated motion, not a moving still image.`;
}
