export type IdeaFeature = 'ai_video' | 'product_images' | 'product_video' | 'web_video' | 'scenario' | 'interior_design';

export interface CreativeIdea {
  id: string;
  feature: IdeaFeature;
  category: string;
  displayText: string;
  masterPrompt: string;
  supportedAspectRatios: Array<'16:9' | '9:16' | '1:1'>;
  requiresReference: boolean;
  optionalReference: boolean;
  tags: string[];
  priority: number;
}

export interface IdeaContext {
  websiteUrl?: string;
  prompt?: string;
  referenceNames?: string[];
  hasReferences?: boolean;
  seed?: number;
}

const ALL_RATIOS: CreativeIdea['supportedAspectRatios'] = ['16:9', '9:16', '1:1'];

const VIDEO_GUARDRAIL = `Respect the user's selected duration, aspect ratio, quality, style and references as authoritative technical settings. Preserve the identity of supplied people, products, places, logos and brand assets. Use coherent geometry, believable perspective, physically plausible motion, intentional visual hierarchy, premium lighting and a strong final hero frame. Do not add random text, fake branding, distorted architecture, warped objects, watermarks, or unreadable lettering. Any exact user wording added after this prompt has priority over creative choices in this direction.`;
const PRODUCT_GUARDRAIL = `Use the supplied product as exact visual ground truth. Preserve its geometry, proportions, materials, colorway, branding, logo, label, packaging and identifiable details. Do not redesign or approximate the product. Build the environment, lighting and composition around the real product rather than regenerating identity-critical details. Respect the selected aspect ratio and quality, keep safe crop margins, and avoid fake text or unrelated brand marks. Any explicit user addition has priority.`;
const WEBSITE_GUARDRAIL = `Use the real captured website pages, actual interface, real branding, brand colors, copy, products/services and website structure as ground truth. Do not invent an unrelated brand, unsupported offer or fake feature. Keep visible copy short, correctly spelled and readable; favor real UI captures for critical website text. Respect the user's selected duration, aspect ratio, quality, style and references. User additions after this prompt have priority.`;
export const INTERIOR_MASTER_PROMPT = `You are AiWebVideo's professional architectural visualization director. Treat the user's references, measurements and explicit constraints as authoritative engineering inputs. Never trade geometric accuracy for creativity. Analyze every reference together before designing, cross-check perspective, preserve the existing shell and produce consistent geometry across all outputs. Do not claim construction-ready accuracy from ordinary photos; when a dimension is not supplied or cannot be reliably verified, avoid invented precision. Optimize for professional client/engineer/architect presentation quality.\n\nTreat every supplied room/shop/property photo, floor-plan image, sketch, elevation and written measurement as engineering reference data. Preserve the existing shell, footprint, ceiling/roof geometry, curves, openings, columns, stairs, doors, windows, built-ins and visible structural constraints unless the user explicitly asks to change them. Explicit numeric measurements supplied by the user are authoritative; never silently rescale them. If a measurement cannot be reliably established from the references, do not invent precision—keep the geometry visually consistent and clearly favor the user's stated dimension. Reconstruct perspective and spatial relationships from all references together, not from one image alone. Respect the requested room type, circulation, clearances, materials, furniture scale, lighting, gypsum/ceiling details, linear or magnetic/track lighting, electrical/architectural elements and design style. Produce professional photorealistic architectural visualization suitable for an engineer, architect, interior designer or real-estate presentation. Keep walls, floor, ceiling and roof planes coherent across views. Avoid impossible furniture, floating objects, warped straight lines, inconsistent windows/doors, changing room dimensions, random fixtures, fake construction details, or decorative elements that violate the supplied geometry. If the user asks for a technical/sketch presentation, create a clean architectural concept/visualization rather than claiming it is a construction-ready drawing. User-provided constraints and measurements have priority over creative additions.`;
const SCENARIO_GUARDRAIL = `Preserve any supplied person, product, place or brand reference. Keep dialogue/performance natural, camera movement physically plausible, pacing intentional and the selected duration/aspect ratio authoritative. Never invent unsupported claims or unreadable on-screen text. User additions have priority.`;

function idea(
  feature: IdeaFeature,
  id: string,
  category: string,
  displayText: string,
  direction: string,
  options: Partial<Pick<CreativeIdea, 'requiresReference' | 'optionalReference' | 'tags' | 'priority' | 'supportedAspectRatios'>> = {},
): CreativeIdea {
  const guardrail = feature === 'interior_design'
    ? INTERIOR_GUARDRAIL
    : feature === 'product_images' || feature === 'product_video'
    ? PRODUCT_GUARDRAIL
    : feature === 'web_video'
      ? WEBSITE_GUARDRAIL
      : feature === 'scenario'
        ? SCENARIO_GUARDRAIL
        : VIDEO_GUARDRAIL;
  return {
    id,
    feature,
    category,
    displayText,
    masterPrompt: `${direction.trim()}\n\n${guardrail}`,
    supportedAspectRatios: options.supportedAspectRatios ?? ALL_RATIOS,
    requiresReference: options.requiresReference ?? false,
    optionalReference: options.optionalReference ?? true,
    tags: options.tags ?? [],
    priority: options.priority ?? 50,
  };
}

const AI_VIDEO: CreativeIdea[] = [
  idea('ai_video','drone-flyover','Drone','Create a cinematic drone flyover of this place',`Create a photorealistic cinema-drone sequence using the supplied location/reference as the exact visual foundation. Begin with a wide elevated establishing view, then execute a smooth stabilized approach with natural parallax, subtle altitude change and a restrained orbit around the main subject. Preserve recognizable architecture, terrain, colors and spatial relationships. Use realistic daylight, atmospheric depth and physically believable shadows; make the result feel captured by an expensive professional drone, not generated.`,{requiresReference:true,tags:['location','hotel','villa','restaurant','property','real-estate','outdoor','travel'],priority:100}),
  idea('ai_video','seamless-fpv','Drone','Fly through this place in one seamless cinematic shot',`Create one seamless stabilized FPV/cinema-camera journey through the referenced environment. Start with a strong exterior or wide establishing composition, approach smoothly, pass through or around the most visually meaningful areas and finish on a deliberate reveal. Maintain spatial continuity, scale, perspective and architecture from shot start to finish. Use realistic motion blur and inertia; avoid impossible clipping, melting geometry or arbitrary scene changes.`,{requiresReference:true,tags:['location','interior','hotel','restaurant','property'],priority:96}),
  idea('ai_video','movie-opening','Cinematic','Turn this scene into an epic movie opening',`Transform the supplied subject or scene into a premium movie-opening sequence. Begin with intrigue and controlled partial information, progressively reveal the primary subject with cinematic lensing, dimensional light and motivated camera movement, then resolve on a powerful hero composition. Keep the world photorealistic, coherent and tonally sophisticated rather than relying on random spectacle.`,{priority:94}),
  idea('ai_video','satellite-ground','Creative','Create a dramatic satellite-to-ground reveal',`Create a dramatic scale transition that begins at an extremely wide earth/environment perspective and progressively accelerates toward the referenced location or primary subject until arriving in an intimate cinematic hero shot. Maintain geographic and architectural consistency throughout the move, use believable atmospheric layers and perspective, and make every scale transition smooth enough to feel intentionally photographed.`,{requiresReference:true,tags:['location','property','travel'],priority:90}),
  idea('ai_video','viral-reel','Social','Make this feel like a viral cinematic Reel',`Build a premium short-form cinematic Reel with an immediate first-second visual hook, purposeful motion, strong subject hierarchy, tasteful speed changes and a memorable final hero moment. Optimize composition and pacing for attention without cheap gimmicks. Keep the core subject visually consistent across the entire sequence.`,{priority:92}),
  idea('ai_video','luxury-slow','Cinematic','Create a slow-motion luxury reveal',`Create an elegant luxury reveal that begins on carefully chosen partial details and gradually exposes the complete subject. Use refined macro/medium shots, slow controlled movement, premium reflections, soft directional highlights and shallow depth of field where appropriate. Finish with a clean, confident hero frame and generous negative space.`,{priority:91}),
  idea('ai_video','cinema-orbit','Camera','Orbit around the subject like a cinema camera',`Create a physically believable smooth camera orbit around the primary subject. Preserve subject proportions while perspective changes naturally; use stable parallax, subtle focus falloff, consistent light direction and realistic lens behavior. The orbit should feel filmed on a professional motion-control rig rather than warped around the subject.`,{priority:88}),
  idea('ai_video','fpv-precision','Camera','Create an FPV fly-through with impossible-looking precision',`Create an energetic stabilized FPV-style move that threads around and through the provided environment with exceptionally precise choreography while still obeying physical space. Use dynamic elevation and direction changes, but maintain coherent ground geometry, realistic speed, inertia and perspective. End the path on a strong planned reveal.`,{requiresReference:true,tags:['location','interior','outdoor'],priority:86}),
  idea('ai_video','living-photo','Transformation','Turn this photo into a living cinematic moment',`Animate the supplied still into a subtle, believable living moment. Preserve the exact composition and subject identity while adding natural environmental motion, restrained camera drift, realistic micro-movements, depth separation and lighting continuity. Avoid exaggerated facial/body changes or invented objects; the result should feel like the photograph came alive for a cinematographer.`,{requiresReference:true,priority:90}),
  idea('ai_video','day-night','Transformation','Make day transform smoothly into night',`Create a continuous photoreal time transition from day to night around the supplied scene. Keep architecture, subject placement and camera geometry locked while sunlight angle, sky color, practical lights, reflections and shadows evolve naturally through golden hour into night. Avoid sudden identity changes or discontinuous object movement.`,{requiresReference:true,tags:['location'],priority:80}),
  idea('ai_video','storm-sun','Transformation','Create a dramatic storm-to-sunlight transformation',`Begin with a believable dramatic storm atmosphere and transition the same scene toward clear warm sunlight. Keep the scene identity fixed while clouds, rain, surface reflections, volumetric light and exposure evolve smoothly. Use the weather change as the narrative arc and end with a hopeful cinematic hero frame.`,{optionalReference:true,priority:74}),
  idea('ai_video','smoke-light','Cinematic','Reveal the subject through smoke and cinematic light',`Stage a restrained premium reveal in which volumetric haze and directional beams initially obscure the subject, then controlled camera movement and shifting light reveal its form. Maintain realistic smoke physics and clean edges; do not bury the subject in effects. End with a crisp hero view.`,{priority:78}),
  idea('ai_video','holographic-world','Creative','Create a futuristic holographic environment around this',`Build a sophisticated futuristic environment around the supplied subject using restrained holographic interfaces, volumetric light and dimensional data-like elements. Keep the real subject untouched and dominant. Make holograms react to perspective and scene lighting so they feel integrated, not pasted on, and avoid unreadable pseudo-text.`,{priority:72}),
  idea('ai_video','race-stop','Camera','Race toward the subject, then stop perfectly',`Design a high-energy camera push that accelerates rapidly toward the main subject, uses believable motion blur and perspective compression, then decelerates cleanly into a perfectly stable hero frame. Preserve geometry throughout the move and make the stop feel mechanically precise rather than abrupt or warped.`,{priority:76}),
  idea('ai_video','sunrise','Cinematic','Create a peaceful sunrise cinematic sequence',`Create a calm premium sunrise sequence centered on the supplied scene or subject. Let cool pre-dawn tones transition into warm directional sunlight, soft atmospheric haze and long natural shadows while the camera moves gently and intentionally. Finish with an optimistic, uncluttered hero frame.`,{tags:['travel','location','wellness'],priority:75}),
  idea('ai_video','travel-commercial','Cinematic','Turn this into a high-end travel commercial',`Create a polished travel-commercial sequence that sells the feeling of being in the referenced place. Use elegant establishing views, human-scale details where supported, smooth aerial/gimbal motion, premium natural light and a clear visual progression from discovery to desire. Never invent architectural or destination details that are not grounded by references.`,{requiresReference:true,tags:['hotel','resort','travel','location','property'],priority:85}),
  idea('ai_video','before-after','Transformation','Create a cinematic before-and-after transformation',`Create a clearly legible before-to-after transformation in one coherent visual language. Establish the original state long enough to understand it, transition with motivated camera/effect movement, then hold the improved/final state in a strong hero composition. Keep unchanged identity-critical details consistent across both states.`,{priority:73}),
  idea('ai_video','space-crashzoom','Creative','Start in space and crash-zoom into this location',`Open from a vast orbital-scale perspective and execute a dramatic but smooth crash-zoom toward the referenced location, progressively resolving atmosphere, terrain and architecture until landing on a precise ground-level cinematic shot. Preserve geographic plausibility and the actual location identity; avoid fantasy map details or geometry morphing.`,{requiresReference:true,tags:['location','property','travel'],priority:82}),
  idea('ai_video','freeze-time','Creative','Freeze time while the camera moves around the scene',`Create a stylized photoreal moment where the main action appears frozen while the camera moves smoothly through three-dimensional space. Preserve subject anatomy and object positions exactly while parallax reveals depth. Keep suspended particles or motion cues physically consistent and end by gently restoring motion.`,{priority:70}),
  idea('ai_video','world-builds','Creative','Make the environment build itself around the subject',`Keep the primary subject stable while its environment assembles around it in a choreographed premium transformation. Introduce architectural, set or environmental elements in logical layers with consistent lighting, shadows and perspective, as though the world is constructing itself. Never alter the identity of a supplied subject or product.`,{priority:69}),
  idea('ai_video','miniature-real','Creative','Transition from miniature world to real scale',`Begin with the scene presented as a convincing handcrafted or miniature-scale world, then transition seamlessly into the same composition at real scale. Use depth of field, lens behavior and camera height to sell the scale change while preserving layout and subject identity. Make the reveal elegant rather than toy-like.`,{priority:66}),
  idea('ai_video','impossible-camera','Camera','Create one impossible seamless camera move',`Design one continuous cinematic camera move that feels surprising yet visually coherent: pass close to foreground detail, reveal a new spatial layer, change elevation or direction, then settle on the hero subject without visible cuts. Preserve geometry and identity throughout so the move feels expertly choreographed rather than randomly generated.`,{priority:83}),
  idea('ai_video','neon-night','Transformation','Turn daytime into a neon night transformation',`Transform the same daytime scene into a premium neon-night version while preserving all important structures and subjects. Evolve sky, exposure, practical lighting, reflections and color accents smoothly; keep the night treatment tasteful and cinematic rather than oversaturated cyberpunk unless the user asks for that style.`,{requiresReference:true,priority:71}),
  idea('ai_video','documentary-close','Cinematic','Create an intimate documentary-style moment',`Create an observational cinematic moment with subtle handheld or stabilized realism, natural performance, authentic environmental detail and restrained lighting. Favor meaningful close/medium framing, believable imperfections and emotional presence rather than commercial gloss, while keeping the supplied subject identity exact.`,{priority:64}),
];

const PRODUCT_IMAGES: CreativeIdea[] = [
  idea('product_images','luxury-studio','Luxury','Create a luxury studio campaign around this product',`Create a premium luxury advertising photograph using the supplied product as the exact hero subject. Place it in an elegant controlled studio with sculpted directional lighting, subtle reflections, precise shadows and sophisticated negative space. Make it feel like a global-brand campaign photographed on a high-end set, not an AI approximation.`,{requiresReference:true,priority:100}),
  idea('product_images','floating-dark','Studio','Make the product float in a premium dark studio',`Place the exact product floating naturally in a deep premium studio environment. Use refined rim lighting, controlled highlights, a believable contact/ambient shadow relationship, restrained atmospheric depth and polished reflections that reveal material quality without changing the product.`,{requiresReference:true,priority:96}),
  idea('product_images','ecommerce-hero','Ecommerce','Create a clean ecommerce hero photo',`Create a conversion-focused ecommerce hero image with the exact product centered or intentionally offset on a clean neutral background. Use soft even lighting, accurate material rendering, crisp edges, realistic shadow grounding and generous safe space for responsive storefront crops. No decorative clutter.`,{requiresReference:true,priority:98}),
  idea('product_images','glossy-surface','Studio','Put this product on a glossy reflective surface',`Photograph the exact product on a premium glossy surface with a physically correct, restrained reflection. Use shaped studio light, clean highlight control, realistic contact shadows and a sophisticated background gradient. Keep the reflection supportive, not distracting.`,{requiresReference:true,priority:90}),
  idea('product_images','water-splash','Creative','Create a dramatic water splash campaign',`Build a high-speed commercial still around the exact product with realistic water motion, droplets and controlled splash arcs. Keep product surfaces, labels and edges unobscured and sharp. Light the water to complement the brand palette and maintain plausible fluid physics.`,{requiresReference:true,priority:86}),
  idea('product_images','pastel-luxury','Luxury','Create a soft luxury pastel campaign',`Place the exact product in a refined pastel campaign world with soft sculptural forms, subtle tonal layering, gentle directional light and elegant shadow design. Keep the palette sophisticated and use contrast to preserve product readability.`,{requiresReference:true,priority:82}),
  idea('product_images','glass-display','Creative','Place this product inside a futuristic glass display',`Present the exact product inside a believable premium glass display or vitrined environment. Use realistic refraction, reflections and edge highlights while keeping the product unobstructed and tack sharp. Make the set futuristic but clean enough for luxury advertising.`,{requiresReference:true,priority:80}),
  idea('product_images','outdoor-lifestyle','Lifestyle','Create an outdoor lifestyle campaign for this product',`Place the exact product in a realistic outdoor context that supports its actual category and use. Use natural golden-hour or soft daylight, believable environmental interaction, premium editorial composition and shallow depth where useful. Do not invent unsupported product functions.`,{requiresReference:true,priority:88}),
  idea('product_images','magazine-ad','Luxury','Make this look like a premium magazine advertisement',`Create an editorial magazine-grade product photograph with disciplined art direction, elegant negative space, sophisticated lighting and a memorable composition. Keep the product exact and leave intentional room for later real text layout rather than generating fake typography.`,{requiresReference:true,priority:84}),
  idea('product_images','spotlight','Studio','Create a dramatic spotlight product reveal',`Use one or two carefully controlled spotlights to reveal the exact product from a darker environment. Sculpt form with clean falloff, precise highlights and realistic shadow density while preserving all label and logo details. Finish with a bold, uncluttered hero composition.`,{requiresReference:true,priority:83}),
  idea('product_images','social-four','Social','Create four social campaign directions',`Create a strong social-campaign visual direction for the exact product with bold hierarchy, mobile-friendly composition and a clear hero focal point. Keep enough layout flexibility that four distinct variations can be generated without changing product identity; vary set, crop and lighting rather than the product itself.`,{requiresReference:true,priority:77}),
  idea('product_images','real-lifestyle','Lifestyle','Place the product in a realistic lifestyle environment',`Integrate the exact product into a believable real-world scene that matches how the product would actually be used or displayed. Match perspective, contact shadows, reflections, color temperature and depth so the product feels photographed in-camera rather than pasted in.`,{requiresReference:true,priority:89}),
  idea('product_images','minimal-tech','Ecommerce','Create a minimalist premium-tech product composition',`Create an ultra-clean premium technology-style composition with the exact product, disciplined geometry, soft neutral gradients, precise edge lighting and abundant negative space. Favor calm confidence and flawless material rendering over decorative props.`,{requiresReference:true,priority:87}),
  idea('product_images','marble-shadow','Luxury','Create an elegant marble and shadow campaign',`Place the exact product on or near sophisticated marble/stone surfaces with tasteful veining, warm directional light and architectural shadow shapes. Keep the set luxurious but restrained and ensure surface reflections and contact shadows remain physically believable.`,{requiresReference:true,priority:79}),
  idea('product_images','neon-campaign','Creative','Create a futuristic neon product campaign',`Build a polished futuristic set around the exact product using controlled colored light, subtle luminous accents and reflective materials. Keep brand/product colors accurate and avoid over-saturating the product itself. The result should feel like a premium launch campaign, not a generic cyberpunk render.`,{requiresReference:true,priority:76}),
  idea('product_images','instagram-launch','Social','Make this perfect for an Instagram product launch',`Create a scroll-stopping Instagram launch image with immediate product recognition, strong 4:5/1:1-safe hierarchy, premium lighting, clean background separation and intentional negative space for real campaign copy. Preserve every identity-critical detail.`,{requiresReference:true,priority:91}),
  idea('product_images','seasonal','Lifestyle','Create a seasonal campaign while preserving the product',`Create a seasonal campaign setting that clearly communicates the requested/current season through tasteful environment, materials, light and props while the exact product remains unchanged and dominant. Avoid cliché clutter; keep the campaign premium and category-appropriate.`,{requiresReference:true,priority:72}),
  idea('product_images','floating-objects','Creative','Create a high-end floating-object composition',`Keep the exact product as the stable hero while complementary category-appropriate elements float around it in a balanced, gravity-defying composition. Use coherent shadows, depth, perspective and motion implication; never obscure branding or key product surfaces.`,{requiresReference:true,priority:78}),
  idea('product_images','glass-break','Creative','Make the product break through a glass-like surface',`Create a dramatic commercial composition where the exact product appears to break through a stylized glass-like plane. Keep fragments and reflections physically coherent, protect the product from distortion, and maintain clear visibility of logo/packaging details.`,{requiresReference:true,priority:68}),
  idea('product_images','particle-appear','Creative','Make the product appear from particles',`Reveal the exact product emerging from finely controlled particles that gather around its silhouette without replacing or morphing the real product. Use realistic depth, lighting and particle falloff so the effect supports the hero object rather than hiding details.`,{requiresReference:true,priority:67}),
  idea('product_images','microscopic-out','Creative','Reveal the product from microscopic details outward',`Compose a premium campaign still inspired by an extreme material/detail study that visually resolves into the complete exact product. Preserve real textures and construction details, using macro lighting and depth to connect material craftsmanship to the final hero view.`,{requiresReference:true,priority:65}),
  idea('product_images','gravity','Creative','Create a gravity-defying product showcase',`Place the exact product in a refined gravity-defying composition with believable orientation, supporting secondary elements and carefully designed shadows/reflections that make the impossible setup feel photographically intentional. Keep the product itself perfectly undistorted.`,{requiresReference:true,priority:70}),
  idea('product_images','monochrome','Studio','Create a monochrome tonal campaign around the product',`Build a sophisticated tonal set using shades related to the product or brand while maintaining enough luminance and edge contrast to keep the exact product readable. Use sculpted light, layered surfaces and restrained shadows for a fashion-editorial finish.`,{requiresReference:true,priority:63}),
  idea('product_images','premium-shelf','Ecommerce','Create a premium retail shelf hero image',`Place the exact product in a clean high-end retail display context with realistic scale, shelf lighting and depth. Keep surrounding products/props abstract or category-neutral so nothing creates fake competing brands or unsupported packaging.`,{requiresReference:true,priority:62}),
];

const PRODUCT_VIDEO: CreativeIdea[] = [
  idea('product_video','luxury-360','Luxury','Create a luxury 360° product reveal',`Create a premium cinematic commercial centered entirely on the supplied product. Begin with a mysterious authentic detail, then reveal the complete product through a smooth motion-control orbit. Use premium studio lighting, realistic reflections, physical shadows and controlled depth of field. Finish on a clean international-campaign hero shot.`,{requiresReference:true,priority:100}),
  idea('product_video','assemble','Reveal','Make the product assemble itself cinematically',`Create a cinematic assembly reveal where components or visual layers come together around the exact supplied product without altering its true geometry or branding. Use precise choreographed motion, physically plausible spacing and a final seamless transition into the untouched complete product.`,{requiresReference:true,priority:91}),
  idea('product_video','impact-drop','Dynamic','Drop the product into frame with a dramatic impact',`Open on a prepared premium set, then bring the exact product into frame with a controlled dramatic drop or landing. Use believable mass, impact timing, dust/splash/light reaction appropriate to the surface, and stabilize into a sharp hero frame without deforming the product.`,{requiresReference:true,priority:88}),
  idea('product_video','smoke-reveal','Reveal','Reveal the product through smoke and light',`Start with the exact product partially concealed by realistic volumetric haze and narrow light. Move the camera and lights in a coordinated reveal that progressively exposes silhouette, material and branding, then clear the atmosphere for a crisp final hero shot.`,{requiresReference:true,priority:89}),
  idea('product_video','floating','Luxury','Create a floating product commercial',`Make the exact product float with subtle believable rotation in a premium studio. Use consistent perspective, controlled momentum, elegant rim light and realistic reflections/shadows on nearby surfaces. Reveal key material details before settling into a stable hero composition.`,{requiresReference:true,priority:95}),
  idea('product_video','viral-tiktok','Social','Create a viral TikTok product reveal',`Create a fast premium vertical-first product reveal with a strong first-second hook, immediate product recognition, purposeful camera motion and rhythmic cuts/effects that never compromise the exact product identity. End on a clean frame designed for a real CTA overlay.`,{requiresReference:true,priority:97}),
  idea('product_video','slow-motion','Luxury','Make a premium slow-motion commercial',`Create a refined slow-motion product film using macro details, graceful motion, carefully controlled highlights and tactile material emphasis. Maintain perfect product consistency between shots and use pacing that builds anticipation toward a pristine final hero shot.`,{requiresReference:true,priority:90}),
  idea('product_video','macro-film','Reveal','Create a macro-detail product film',`Build the commercial from authentic extreme close details of the exact product—material texture, hardware, stitching, finish or packaging details—then progressively widen until the complete product is revealed. Keep macro geometry accurate and lighting consistent across the reveal.`,{requiresReference:true,priority:93}),
  idea('product_video','future-launch','Creative','Turn this into a futuristic product launch',`Create a premium future-facing launch environment around the exact product using dimensional light, restrained holographic accents and sophisticated motion graphics without generating fake text. Let the world react to the product while the product itself remains unchanged and sharply recognizable.`,{requiresReference:true,priority:83}),
  idea('product_video','fashion-campaign','Luxury','Create an elegant fashion-style campaign video',`Direct the exact product as the hero of an editorial fashion campaign with confident compositions, smooth lens movement, tactile close-ups, elegant lighting and deliberate pacing. Keep styling sophisticated and avoid visual effects that distort shape, labels or materials.`,{requiresReference:true,tags:['shoe','fashion','clothes','bag'],priority:86}),
  idea('product_video','water-emerge','Dynamic','Make the product emerge from water',`Reveal the exact product rising from or being uncovered by realistic water with controlled droplets, reflections and ripples. Protect branding and critical product surfaces from obscuration, keep fluid interaction physically plausible, then finish dry/clear enough for a sharp hero view.`,{requiresReference:true,priority:79}),
  idea('product_video','world-build','Creative','Build a cinematic environment around the product',`Keep the exact product locked as the central hero while a premium environment assembles around it in choreographed layers. Match perspective, shadows, reflections and lighting as each element arrives; the environment should amplify the product category and brand mood without changing the product.`,{requiresReference:true,priority:82}),
  idea('product_video','package-open','Reveal','Make the packaging open into a premium reveal',`Use the real supplied packaging/product identity to create a believable opening reveal. Let package movement feel mechanically plausible, preserve printed branding and proportions, reveal the product cleanly without redesigning it, and finish with package and product arranged in a premium hero composition.`,{requiresReference:true,priority:84}),
  idea('product_video','clean-minimal','Minimal','Create a clean minimal commercial',`Create a disciplined minimal product film on a simple premium set. Use smooth motion-control camera moves, precise light changes, clean shadows and only essential transitions. Give the exact product uninterrupted visual priority and end with generous negative space.`,{requiresReference:true,priority:94}),
  idea('product_video','high-energy','Social','Create a high-energy social ad',`Build a high-energy short social commercial with immediate product recognition, fast but readable shot progression, purposeful match cuts, dynamic camera moves and a final confident hero hold. Keep every frame grounded in the exact supplied product; energy must come from editing and cinematography, not identity distortion.`,{requiresReference:true,priority:87}),
  idea('product_video','detail-to-hero','Reveal','Show the product from detail to hero shot',`Open on one distinctive real product detail, move through two or three meaningful material/feature views, then reveal the full exact product with a smooth visual payoff. Use consistent light and geometry so every detail clearly belongs to the same item.`,{requiresReference:true,priority:92}),
  idea('product_video','brand-launch','Luxury','Turn this into a luxury brand launch',`Create a restrained premium brand-launch film around the exact product. Use elegant pacing, sculpted studio light, refined movement, tactile close-ups and a memorable final hero frame. Avoid fake slogans or generated logo text; leave clean space for real brand typography.`,{requiresReference:true,priority:96}),
  idea('product_video','glass-break','Dynamic','Make the product break through a glass-like surface',`Create a controlled impact reveal where the exact product passes through a stylized glass-like plane. Keep fragments, highlights and camera motion coherent while the product remains pristine, undistorted and readable. Use the effect once as a premium hook, not continuous visual noise.`,{requiresReference:true,priority:70}),
  idea('product_video','particles','Creative','Make the product materialize from particles',`Begin with a refined field of particles that progressively resolves around the silhouette of the exact product, then transition to the untouched real product for the remainder of the shot. Keep brand marks and physical details protected from generative morphing.`,{requiresReference:true,priority:68}),
  idea('product_video','pedestal-orbit','Minimal','Orbit a premium pedestal reveal',`Place the exact product on a clean architectural pedestal and execute a subtle coordinated pedestal/camera orbit. Use changing highlights to reveal material quality, maintain stable geometry and finish in the strongest front/three-quarter hero angle.`,{requiresReference:true,priority:80}),
  idea('product_video','shadow-play','Creative','Reveal the product with moving light and shadows',`Keep the exact product stable while carefully designed light and shadow movement travels across the set and product surfaces, progressively revealing shape and material. Use realistic light direction and keep labels/logos readable at the final reveal.`,{requiresReference:true,priority:76}),
  idea('product_video','new-drop','Social','Create a premium new-drop campaign',`Create a fashion/product new-drop style launch with an immediate visual hook, compact premium pacing, close material details, one signature movement and a strong final hero frame designed for mobile social placement. Never alter the exact product colorway or branding.`,{requiresReference:true,priority:85}),
  idea('product_video','one-take','Creative','Reveal this product in one seamless camera move',`Design one continuous shot that begins on an authentic detail, glides around or past the exact product, changes scale smoothly and resolves on the complete hero composition without visible cuts. Keep the motion physically achievable and the product geometry locked.`,{requiresReference:true,priority:81}),
  idea('product_video','lifestyle-transition','Dynamic','Transition from studio hero to real lifestyle use',`Begin with the exact product in a clean studio hero setup, then transition seamlessly into a believable lifestyle context appropriate to the product category. Preserve scale, orientation, color and identity across the transition; never imply unsupported functionality.`,{requiresReference:true,priority:75}),
];

const INTERIOR_DESIGN: CreativeIdea[] = [
  idea('interior_design','existing-space-redesign','Interior','Redesign this exact space without changing its architecture',`Create a high-end architectural interior redesign from the supplied photos and references. Keep the exact footprint and visible architecture while replacing finishes, furniture, colors and lighting according to the user's direction. Analyze the room from every supplied view before designing. Preserve ceiling height, roof shape, curves, openings and circulation.`,{requiresReference:true,tags:['home','shop','office','real-estate','room','architecture'],priority:100}),
  idea('interior_design','engineer-concept','Technical','Turn this into a professional engineer-style interior concept',`Create a professional architectural concept visualization based on the supplied photos, sketches, plans and dimensions. Show the proposed layout, ceiling/gypsum treatment, material transitions, lighting positions and built-in elements with disciplined geometry and presentation-quality realism. Treat measurements and structural constraints as source data, not decoration.`,{requiresReference:true,tags:['engineer','architect','plan','measurements','shop','real-estate'],priority:99}),
  idea('interior_design','shop-fitout','Commercial','Design a complete retail shop fit-out',`Redesign the supplied retail/commercial space as a complete professional fit-out. Preserve the exact shell and dimensions, then develop customer circulation, display walls, counters, storage, signage zones, ceiling/gypsum details, practical lighting and premium material hierarchy. Keep the result buildable-looking and consistent with the supplied space.`,{requiresReference:true,tags:['shop','retail','store','commercial'],priority:98}),
  idea('interior_design','real-estate-staging','Real Estate','Create a premium real-estate interior proposal',`Transform the supplied property into a polished real-estate interior proposal while preserving actual room proportions, openings and architectural features. Use furniture at realistic scale, coherent finishes, layered lighting and a refined material palette. Make the result suitable for client presentation and property marketing without inventing rooms or changing the shell.`,{requiresReference:true,tags:['real-estate','villa','apartment','property'],priority:96}),
  idea('interior_design','ceiling-lighting','Ceiling','Design the ceiling, gypsum and lighting system',`Focus on the supplied ceiling/roof geometry and develop a premium ceiling concept with gypsum details, coves, linear lighting, magnetic/track lighting, spots and indirect illumination where appropriate. Preserve ceiling height, beams, curves and structural constraints visible in the references. Make light sources physically plausible and coordinated with the interior.`,{requiresReference:true,tags:['ceiling','gypsum','linear','magnetic','lighting','roof'],priority:97}),
  idea('interior_design','materials-board','Materials','Create a complete material and finish direction',`Develop a cohesive architectural material direction for the exact supplied space: flooring, walls, ceiling, joinery, stone, wood, metal, glass and upholstery as appropriate. Preserve geometry and use realistic scale, seams, edge conditions and light response. Present the result as a premium design proposal rather than random decoration.`,{requiresReference:true,tags:['materials','stone','wood','marble','joinery'],priority:88}),
  idea('interior_design','before-after','Transformation','Create a precise before-and-after interior transformation',`Create a clear before-and-after transformation of the exact supplied space. Keep camera position, perspective, room dimensions and architectural shell aligned between the original and proposed design so the client can directly compare what changed. Highlight finishes, furniture, ceiling and lighting changes without changing unrelated geometry.`,{requiresReference:true,priority:94}),
  idea('interior_design','walkthrough','Video','Create a professional interior walkthrough',`Create one continuous premium architectural walkthrough of the proposed interior. Camera height, lens, room scale and spatial relationships must remain physically consistent. Move through the actual supplied layout, reveal the strongest design details, show ceiling and lighting treatment, and finish on a clear hero view. Do not invent corridors, rooms or openings that are not supported by references.`,{requiresReference:true,tags:['tour','walkthrough','real-estate','architecture'],priority:100}),
  idea('interior_design','cinematic-real-estate','Video','Create a cinematic real-estate interior tour',`Create a polished real-estate film from the proposed interior. Use slow stabilized camera movement, natural daylight plus designed practical lighting, realistic materials and carefully chosen reveals. Preserve exact room geometry and keep furniture scale believable throughout the continuous sequence.`,{requiresReference:true,tags:['real-estate','property','villa','apartment'],priority:92}),
  idea('interior_design','luxury-modern','Style','Design a luxury modern interior',`Develop a sophisticated contemporary interior using the supplied architecture as the immutable base. Favor disciplined proportions, premium materials, layered warm/cool lighting, custom joinery and restrained furniture. Preserve the actual shell, openings and dimensions while making the design feel internationally high-end.`,{requiresReference:true,priority:91}),
  idea('interior_design','minimalist','Style','Design a refined minimalist interior',`Create a calm minimalist interior with clean planes, concealed storage, restrained materials, integrated lighting and precise furniture placement. Preserve all supplied architectural constraints and dimensions. Every element should have a reason and believable scale; avoid empty-looking or impractical spaces.`,{requiresReference:true,priority:86}),
  idea('interior_design','multiple-angles','Technical','Generate consistent design views from multiple angles',`Generate a consistent architectural design set from the supplied references. Maintain the same walls, openings, ceiling, floor, furniture dimensions and materials across each requested viewpoint. Treat the first reference as geometry evidence and all additional references as cross-checks; never let a new camera angle silently change the space.`,{requiresReference:true,priority:98}),
];

const WEB_VIDEO: CreativeIdea[] = [
  idea('web_video','premium-launch','Launch','Turn this website into a premium launch trailer',`Create a polished launch film for this exact website. Open with the strongest authentic brand/UI hook, reveal the most important pages or features through cinematic interface movement, focus on genuine benefits rather than random scrolling, and finish with a clear real call-to-action drawn from the site. Use tasteful depth and premium motion design while keeping the real interface recognizable.`,{priority:100}),
  idea('web_video','global-tech','Launch','Make this website feel like a global tech launch',`Present the real website like a global technology launch: confident opening, clean dimensional UI reveals, precise motion, high-end lighting/depth treatment and a structured progression from value proposition to core workflow to CTA. Keep actual website screens and claims intact.`,{tags:['saas','software','app','platform'],priority:94}),
  idea('web_video','feature-tour','Product Tour','Show the best features in a cinematic product tour',`Identify the strongest real features visible in the captured website and create a cinematic guided tour that gives each feature enough screen time to understand. Use smooth focus moves, intelligent zooms and clean transitions between real UI states, ending on the most important action.`,{priority:96}),
  idea('web_video','viral-reel','Social','Turn this website into a viral Reel',`Create a premium short-form Reel from the real website with a strong first-second hook, fast readable UI highlights, bold but tasteful pacing and a memorable CTA. Keep essential interface text legible and avoid gimmicks that obscure how the site actually works.`,{priority:91}),
  idea('web_video','3d-showcase','3D','Create a premium 3D website showcase',`Place real captured website screens into a sophisticated dimensional presentation with subtle perspective, layered depth, premium camera motion and realistic light/shadow. Screens must remain readable and undistorted; use 3D framing to elevate the real site, not replace it.`,{priority:88}),
  idea('web_video','floating-devices','3D','Make the website appear inside floating devices',`Present the real website inside a small set of premium floating device frames sized appropriately for each captured desktop/mobile screen. Use realistic perspective, reflections and depth while camera motion reveals different real site sections. Keep devices secondary to the actual interface.`,{priority:87}),
  idea('web_video','problem-solution','Conversion','Create a problem-to-solution website advertisement',`Build a concise narrative that establishes the customer problem using only claims supported by the website, then reveal this exact website as the solution, demonstrate the strongest real workflow/benefit and finish on the site's genuine conversion action. Keep the story specific and credible.`,{priority:95}),
  idea('web_video','homepage-story','Brand Story','Turn the homepage into a cinematic brand story',`Use the real homepage structure as a narrative backbone: opening proposition, key visual/benefit, proof or product/service detail, then CTA. Transform scrolling and section changes into one cohesive cinematic brand story while preserving the website's actual visual identity.`,{priority:90}),
  idea('web_video','conversion-social','Conversion','Create a fast conversion-focused social ad',`Create a direct-response social video from the real website. Hook immediately with the strongest authentic value proposition, show the minimum real UI needed to prove it, emphasize one or two genuine benefits and end with a clean CTA from the site. Optimize pacing for mobile while keeping text readable.`,{priority:93}),
  idea('web_video','easy-to-use','Product Tour','Show how easy this website is to use',`Demonstrate a real simple user path through the captured site, using clear cursor/focus-style movement and smooth transitions to show how a visitor completes an important action. Keep every step grounded in the actual UI and avoid inventing interactions that were not captured.`,{priority:86}),
  idea('web_video','luxury-web','Brand Story','Create a luxury commercial for this website',`Turn the real website into a restrained luxury commercial with elegant pacing, premium depth, carefully timed interface reveals and sophisticated visual hierarchy. Preserve the site's actual typography/colors and avoid overselling; let real imagery and interface details feel expensive through direction.`,{priority:82}),
  idea('web_video','app-launch','Launch','Turn this website into an app-style product launch',`Present the real website as a polished digital product launch, emphasizing its interface system, workflow and primary outcome through crisp screen transitions and device-aware compositions. Use app-launch pacing while never pretending the website has screens or features not captured.`,{tags:['saas','app','software'],priority:85}),
  idea('web_video','ui-alive','3D','Make the UI come alive around the viewer',`Use the real interface as layered visual material: cards, sections and screenshots can lift into dimensional space, reassemble and guide the viewer through the site's value. Preserve actual UI pixels and text on important elements; animation should clarify hierarchy instead of inventing new interface content.`,{priority:84}),
  idea('web_video','linkedin','Social','Create a clean LinkedIn launch video',`Create a professional LinkedIn-ready launch video using the real website. Lead with a concise business value proposition, show the strongest authentic workflow or differentiator, use restrained premium motion and end with a clear next step. Keep pacing confident, informative and readable without hype.`,{priority:89}),
  idea('web_video','tiktok-web','Social','Create a bold TikTok website commercial',`Create a vertical-first TikTok commercial from the actual site with an immediate visual hook, quick but understandable screen reveals, energetic transitions and a clear payoff. Keep real UI readable and use camera/editing energy instead of fake interface text or unsupported claims.`,{priority:88}),
  idea('web_video','future-interface','3D','Turn this website into a futuristic interface reveal',`Place the real website screens in a clean futuristic dimensional environment with subtle luminous accents, depth and motion. Keep the actual interface as the source of truth and avoid fake holographic text; the futuristic treatment should frame and reveal the real product, not redesign it.`,{priority:78}),
  idea('web_video','web-to-real','Brand Story','Create a cinematic website-to-real-world transition',`Begin inside the real captured website, select an authentic product/service/location visual, then transition cinematically into a grounded real-world style scene only where references support it. Return to the real website for the CTA, preserving a clear connection between digital discovery and actual outcome.`,{priority:80}),
  idea('web_video','customer-journey','Conversion','Show the customer journey from visit to action',`Use real captured pages to demonstrate the customer journey from landing/discovery through the most important consideration step to the website's genuine action such as buy, book, contact, sign up or order. Keep the sequence accurate and conversion-focused.`,{priority:97}),
  idea('web_video','before-after-discovery','Brand Story','Create a before-discovering vs after-discovering story',`Create a concise contrast narrative showing the user's problem/state before discovering the website and the outcome enabled by the website afterward, using only outcomes supported by real site content. Make the website reveal the turning point and end with its authentic CTA.`,{priority:79}),
  idea('web_video','location-drone-site','Brand Story','Fly over the location, then reveal the website',`If reliable location imagery is available, begin with a realistic drone-inspired establishing sequence that preserves the actual physical place, then transition seamlessly into the real website interface and highlight the most important booking/menu/property/service action. If the physical place is not visually grounded, keep the opening abstract rather than inventing architecture.`,{requiresReference:true,tags:['hotel','resort','restaurant','cafe','property','real-estate','venue','gym','clinic','store','location'],priority:99}),
  idea('web_video','destination','Brand Story','Turn this place into a luxury destination commercial',`Use reliable place imagery and the real website together to create a luxury destination film: establish the actual location, reveal authentic atmosphere/details, then connect naturally into the real site for booking, menu, service or contact. Never fabricate exact architecture or amenities absent from the references/site.`,{requiresReference:true,tags:['hotel','resort','restaurant','travel','location'],priority:88}),
  idea('web_video','scroll-one-move','3D','Turn scrolling into one continuous cinematic camera move',`Transform the real website's captured section sequence into one continuous cinematic movement that feels like the camera travels through the page rather than jump-cutting between screenshots. Preserve layout/text fidelity and use depth/parallax to connect authentic sections smoothly.`,{priority:83}),
  idea('web_video','screen-world','Creative','Pull the viewer through the screen into the website',`Open on a real website screen, push the camera through a meaningful visual element and transition into a dimensional interpretation of that authentic product/service world, then return to the actual interface for proof and CTA. Keep any real-world interpretation grounded in available visuals and claims.`,{priority:76}),
  idea('web_video','sections-real','Creative','Make website sections become real-world scenes',`Use selected real website sections as portals into tasteful real-world visualizations of the products/services they genuinely represent. Transition back and forth while preserving exact UI screenshots for important information. Do not invent products, locations or claims not supported by the site.`,{priority:74}),
  idea('web_video','ecom-shopping','Conversion','Turn the store into a premium shopping commercial',`Use real ecommerce pages and product captures to build a premium shopping commercial from discovery to product detail to cart/checkout intent. Make actual products the visual heroes, keep prices/text only when captured clearly, and end on the real purchase action.`,{tags:['ecommerce','shop','store','product'],priority:98}),
  idea('web_video','best-sellers','Product Tour','Create a cinematic best-sellers showcase',`Select the strongest real products visible in the captured store and showcase them with premium screen motion, focused product crops and clean transitions while preserving their actual appearance. Avoid inventing rankings or “best seller” claims unless the website supports them; otherwise frame them as featured products.`,{tags:['ecommerce','shop','store'],priority:87}),
  idea('web_video','saas-workflow','Product Tour','Show the product workflow clearly and cinematically',`Use the actual SaaS/software screens to show one meaningful end-to-end workflow with a clear start, key interaction/result and payoff. Keep the sequence faithful to captured UI and use premium motion to explain rather than distract.`,{tags:['saas','software','platform','dashboard'],priority:98}),
  idea('web_video','restaurant-order','Conversion','Show the customer journey from menu to order',`Use the real restaurant website, actual menu/food imagery and ordering/booking screens to show a believable journey from appetite/discovery through choosing an item/table to the genuine order or booking action. Never invent dishes not shown on the site.`,{tags:['restaurant','cafe','food'],priority:96}),
  idea('web_video','property-reveal','Brand Story','Create a cinematic drone property reveal',`Use reliable property imagery to establish the actual property with a realistic aerial-inspired reveal, then transition into the real listing website for authentic details and the contact/booking action. Preserve true exterior/interior features and never invent architecture beyond the supplied listing/reference.`,{requiresReference:true,tags:['real-estate','property','villa','listing'],priority:97}),
];

const SCENARIO: CreativeIdea[] = [
  idea('scenario','founder','Performance','Have the founder explain the product naturally',`Create a natural founder-led explanation in a clean believable setting. The speaker should sound conversational rather than scripted, use concise sentences, demonstrate or reference only real product benefits, and maintain comfortable eye contact and realistic gestures. End with a short authentic next step.`,{priority:95}),
  idea('scenario','two-person','Performance','Create a natural two-person product conversation',`Stage a believable two-person conversation where one person has a real question/problem and the other naturally explains the product/service. Use reaction shots, subtle overlaps and human pacing rather than alternating monologues. Keep claims grounded in the user's brief.`,{priority:92}),
  idea('scenario','testimonial','Social','Create a warm customer testimonial scene',`Create an authentic customer-testimonial style scene with natural phrasing, specific but supported benefits and restrained emotion. Avoid exaggerated claims or fake statistics. Use intimate framing and believable ambient movement so it feels captured, not performed by an ad actor.`,{priority:90}),
  idea('scenario','podcast','Social','Turn this into a premium podcast-style clip',`Stage the message as a polished conversational podcast/interview excerpt with natural turn-taking, clean close/medium coverage, subtle camera changes and high-quality studio ambience. Keep the content concise enough to fit the selected duration without rushed speech.`,{priority:82}),
  idea('scenario','demo-dialogue','Performance','Explain the workflow while using the product',`Create a performance-led demonstration where the speaker naturally uses or points to the real product/interface while explaining the key workflow. Keep actions synchronized with what is being said and do not invent steps or features unsupported by the prompt/reference.`,{priority:88}),
  idea('scenario','street-interview','Social','Create a polished street-interview style reaction',`Create a believable quick street-interview style exchange with natural body language, concise question/answer structure and documentary camera energy. Keep audio/performance clean and avoid caricature or exaggerated reactions.`,{priority:70}),
  idea('scenario','problem-solution','Performance','Act out the problem, then reveal the solution',`Create a compact scene that first shows the user's described problem through believable action/dialogue, then introduces the product/service as the solution and demonstrates the supported outcome. Make the transition clear and keep the final line concise.`,{priority:85}),
  idea('scenario','direct-camera','Performance','Deliver a confident direct-to-camera launch message',`Create a confident direct-to-camera launch performance with one strong opening line, two or three concise supporting points and a clean close. Use natural gestures, professional but human delivery and subtle cinematic camera movement without overacting.`,{priority:87}),
];

export const CREATIVE_IDEAS: Record<IdeaFeature, CreativeIdea[]> = {
  ai_video: AI_VIDEO,
  product_images: PRODUCT_IMAGES,
  product_video: PRODUCT_VIDEO,
  web_video: WEB_VIDEO,
  scenario: SCENARIO,
  interior_design: INTERIOR_DESIGN,
};

const INTENT_FEATURE = {
  website: 'web_video',
  video: 'ai_video',
  photo: 'product_images',
  'product-video': 'product_video',
  scenario: 'scenario',
  interior: 'interior_design',
} as const;

export type IdeaIntent = keyof typeof INTENT_FEATURE;
export function featureForIntent(intent: IdeaIntent): IdeaFeature { return INTENT_FEATURE[intent]; }

function contextTokens(context: IdeaContext) {
  return `${context.websiteUrl ?? ''} ${context.prompt ?? ''} ${(context.referenceNames ?? []).join(' ')}`.toLowerCase();
}

function scoreIdea(item: CreativeIdea, context: IdeaContext) {
  const tokens = contextTokens(context);
  let score = item.priority;
  for (const tag of item.tags) if (tokens.includes(tag.toLowerCase())) score += 35;
  if (item.requiresReference && !context.hasReferences) score -= 14;
  if (item.requiresReference && context.hasReferences) score += 8;
  const seed = context.seed ?? 0;
  let hash = seed + 17;
  for (const ch of item.id) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
  score += (hash % 13) / 10;
  return score;
}

export function getIdeasForIntent(intent: IdeaIntent, context: IdeaContext = {}, limit = 8) {
  return [...CREATIVE_IDEAS[featureForIntent(intent)]]
    .sort((a, b) => scoreIdea(b, context) - scoreIdea(a, context))
    .slice(0, Math.max(1, limit));
}

export function referenceHintForIdea(item: CreativeIdea, context: IdeaContext) {
  return item.requiresReference && !context.hasReferences
    ? 'Add a photo or reference for a more accurate result.'
    : null;
}
