export type IdeaFeature = 'ai_video' | 'product_images' | 'product_video' | 'web_video' | 'scenario' | 'interior_design' | 'architecture';

export interface CreativeIdea {
  id: string;
  feature: IdeaFeature;
  category: string;
  displayText: string;
  masterPrompt: string;
  supportedAspectRatios: Array<'16:9' | '9:16' | '1:1'>;
  requiresReference: boolean;
  optionalReference: boolean;
  tags: string[];
  priority: number;
}

export interface IdeaContext {
  websiteUrl?: string;
  prompt?: string;
  referenceNames?: string[];
  hasReferences?: boolean;
  seed?: number;
}

const ALL_RATIOS: CreativeIdea['supportedAspectRatios'] = ['16:9', '9:16', '1:1'];

const VIDEO_GUARDRAIL = `Respect the user's selected duration, aspect ratio, quality, style and references as authoritative technical settings. Preserve the identity of supplied people, products, places, logos and brand assets. Use coherent geometry, believable perspective, physically plausible motion, intentional visual hierarchy, premium lighting and a strong final hero frame. Do not add random text, fake branding, distorted architecture, warped objects, watermarks, or unreadable lettering. Any exact user wording added after this prompt has priority over creative choices in this direction.`;
const PRODUCT_GUARDRAIL = `Use the supplied product as exact visual ground truth. Preserve its geometry, proportions, materials, colorway, branding, logo, label, packaging and identifiable details. Do not redesign or approximate the product. Build the environment, lighting and composition around the real product rather than regenerating identity-critical details. Respect the selected aspect ratio and quality, keep safe crop margins, and avoid fake text or unrelated brand marks. Any explicit user addition has priority.`;
const WEBSITE_GUARDRAIL = `Use the real captured website pages, actual interface, real branding, brand colors, copy, products/services and website structure as ground truth. Do not invent an unrelated brand, unsupported offer or fake feature. Keep visible copy short, correctly spelled and readable; favor real UI captures for critical website text. Respect the user's selected duration, aspect ratio, quality, style and references. User additions after this prompt have priority.`;
export const INTERIOR_MASTER_PROMPT = `You are AiWebVideo's professional architectural visualization director. Treat the user's references, measurements and explicit constraints as authoritative engineering inputs. Never trade geometric accuracy for creativity. Analyze every reference together before designing, cross-check perspective, preserve the existing shell and produce consistent geometry across all outputs. Do not claim construction-ready accuracy from ordinary photos; when a dimension is not supplied or cannot be reliably verified, avoid invented precision. Optimize for professional client/engineer/architect presentation quality.\n\nTreat every supplied room/shop/property photo, floor-plan image, sketch, elevation and written measurement as engineering reference data. Preserve the existing shell, footprint, ceiling/roof geometry, curves, openings, columns, stairs, doors, windows, built-ins and visible structural constraints unless the user explicitly asks to change them. Explicit numeric measurements supplied by the user are authoritative; never silently rescale them. If a measurement cannot be reliably established from the references, do not invent precision—keep the geometry visually consistent and clearly favor the user's stated dimension. Reconstruct perspective and spatial relationships from all references together, not from one image alone. Respect the requested room type, circulation, clearances, materials, furniture scale, lighting, gypsum/ceiling details, linear or magnetic/track lighting, electrical/architectural elements and design style. Produce professional photorealistic architectural visualization suitable for an engineer, architect, interior designer or real-estate presentation. Keep walls, floor, ceiling and roof planes coherent across views. Avoid impossible furniture, floating objects, warped straight lines, inconsistent windows/doors, changing room dimensions, random fixtures, fake construction details, or decorative elements that violate the supplied geometry. If the user asks for a technical/sketch presentation, create a clean architectural concept/visualization rather than claiming it is a construction-ready drawing. User-provided constraints and measurements have priority over creative additions.`;
// The full interior/architecture master direction is added on the server; ideas only carry their own direction.
const INTERIOR_GUARDRAIL = `Follow the supplied references and every numeric input exactly. The customer's own words override this direction.`;
const SCENARIO_GUARDRAIL = `Preserve any supplied person, product, place or brand reference. Keep dialogue/performance natural, camera movement physically plausible, pacing intentional and the selected duration/aspect ratio authoritative. Never invent unsupported claims or unreadable on-screen text. User additions have priority.`;

function idea(
  feature: IdeaFeature,
  id: string,
  category: string,
  displayText: string,
  direction: string,
  options: Partial<Pick<CreativeIdea, 'requiresReference' | 'optionalReference' | 'tags' | 'priority' | 'supportedAspectRatios'>> = {},
): CreativeIdea {
  const guardrail = feature === 'interior_design' || feature === 'architecture'
    ? INTERIOR_GUARDRAIL
    : feature === 'product_images' || feature === 'product_video'
    ? PRODUCT_GUARDRAIL
    : feature === 'web_video'
      ? WEBSITE_GUARDRAIL
      : feature === 'scenario'
        ? SCENARIO_GUARDRAIL
        : VIDEO_GUARDRAIL;
  return {
    id,
    feature,
    category,
    displayText,
    masterPrompt: `${direction.trim()}\n\n${guardrail}`,
    supportedAspectRatios: options.supportedAspectRatios ?? ALL_RATIOS,
    requiresReference: options.requiresReference ?? false,
    optionalReference: options.optionalReference ?? true,
    tags: options.tags ?? [],
    priority: options.priority ?? 50,
  };
}

const AI_VIDEO: CreativeIdea[] = [
  idea('ai_video','drone-flyover','Drone','Create a cinematic drone flyover of this place',`Create a photorealistic cinema-drone sequence using the supplied location/reference as the exact visual foundation. Begin with a wide elevated establishing view, then execute a smooth stabilized approach with natural parallax, subtle altitude change and a restrained orbit around the main subject. Preserve recognizable architecture, terrain, colors and spatial relationships. Use realistic daylight, atmospheric depth and physically believable shadows; make the result feel captured by an expensive professional drone, not generated.`,{requiresReference:true,tags:['location','hotel','villa','restaurant','property','real-estate','outdoor','travel'],priority:100}),
  idea('ai_video','seamless-fpv','Drone','Fly through this place in one seamless cinematic shot',`Create one seamless stabilized FPV/cinema-camera journey through the referenced environment. Start with a strong exterior or wide establishing composition, approach smoothly, pass through or around the most visually meaningful areas and finish on a deliberate reveal. Maintain spatial continuity, scale, perspective and architecture from shot start to finish. Use realistic motion blur and inertia; avoid impossible clipping, melting geometry or arbitrary scene changes.`,{requiresReference:true,tags:['location','interior','hotel','restaurant','property'],priority:96}),
  idea('ai_video','movie-opening','Cinematic','Turn this scene into an epic movie opening',`Transform the supplied subject or scene into a premium movie-opening sequence. Begin with intrigue and controlled partial information, progressively reveal the primary subject with cinematic lensing, dimensional light and motivated camera movement, then resolve on a powerful hero composition. Keep the world photorealistic, coherent and tonally sophisticated rather than relying on random spectacle.`,{priority:94}),
  idea('ai_video','satellite-ground','Creative','Create a dramatic satellite-to-ground reveal',`Create a dramatic scale transition that begins at an extremely wide earth/environment perspective and progressively accelerates toward the referenced location or primary subject until arriving in an intimate cinematic hero shot. Maintain geographic and architectural consistency throughout the move, use believable atmospheric layers and perspective, and make every scale transition smooth enough to feel intentionally photographed.`,{requiresReference:true,tags:['location','property','travel'],priority:90}),
  idea('ai_video','viral-reel','Social','Make this feel like a viral cinematic Reel',`Build a premium short-form cinematic Reel with an immediate first-second visual hook, purposeful motion, strong subject hierarchy, tasteful speed changes and a memorable final hero moment. Optimize composition and pacing for attention without cheap gimmicks. Keep the core subject visually consistent across the entire sequence.`,{priority:92}),
  idea('ai_video','luxury-slow','Cinematic','Create a slow-motion luxury reveal',`Create an elegant luxury reveal that begins on carefully chosen partial details and gradually exposes the complete subject. Use refined macro/medium shots, slow controlled movement, premium reflections, soft directional highlights and shallow depth of field where appropriate. Finish with a clean, confident hero frame and generous negative space.`,{priority:91}),
  idea('ai_video','cinema-orbit','Camera','Orbit around the subject like a cinema camera',`Create a physically believable smooth camera orbit around the primary subject. Preserve subject proportions while perspective changes naturally; use stable parallax, subtle focus falloff, consistent light direction and realistic lens behavior. The orbit should feel filmed on a professional motion-control rig rather than warped around the subject.`,{priority:88}),
  idea('ai_video','fpv-precision','Camera','Create an FPV fly-through with impossible-looking precision',`Create an energetic stabilized FPV-style move that threads around and through the provided environment with exceptionally precise choreography while still obeying physical space. Use dynamic elevation and direction changes, but maintain coherent ground geometry, realistic speed, inertia and perspective. End the path on a strong planned reveal.`,{requiresReference:true,tags:['location','interior','outdoor'],priority:86}),
  idea('ai_video','living-photo','Transformation','Turn this photo into a living cinematic moment',`Animate the supplied still into a subtle, believable living moment. Preserve the exact composition and subject identity while adding natural environmental motion, restrained camera drift, realistic micro-movements, depth separation and lighting continuity. Avoid exaggerated facial/body changes or invented objects; the result should feel like the photograph came alive for a cinematographer.`,{requiresReference:true,priority:90}),
  idea('ai_video','day-night','Transformation','Make day transform smoothly into night',`Lock the camera in place and let a whole day pass over the scene: shadows sweep and lengthen, the sky shifts through golden hour and dusk to a deep star-filled night, and windows and lights switch on one after another. The framing never moves; only light and time change, smoothly and continuously.`,{requiresReference:true,tags:['location'],priority:80}),
  idea('ai_video','storm-sun','Transformation','Create a dramatic storm-to-sunlight transformation',`Start under a heavy, bruised sky with wind-bent trees and driving rain. Then the clouds tear open, hard shafts of sunlight sweep across the scene, wet surfaces ignite with highlights and the mood lifts from tension to relief as the camera rises slowly. Keep the subject recognizable throughout.`,{optionalReference:true,priority:74}),
  idea('ai_video','smoke-light','Cinematic','Reveal the subject through smoke and cinematic light',`Stage a restrained premium reveal in which volumetric haze and directional beams initially obscure the subject, then controlled camera movement and shifting light reveal its form. Maintain realistic smoke physics and clean edges; do not bury the subject in effects. End with a crisp hero view.`,{priority:78}),
  idea('ai_video','holographic-world','Creative','Create a futuristic holographic environment around this',`Build a sophisticated futuristic environment around the supplied subject using restrained holographic interfaces, volumetric light and dimensional data-like elements. Keep the real subject untouched and dominant. Make holograms react to perspective and scene lighting so they feel integrated, not pasted on, and avoid unreadable pseudo-text.`,{priority:72}),
  idea('ai_video','race-stop','Camera','Race toward the subject, then stop perfectly',`Open with a blinding speed-ramped rush: streaking light, stretched motion and rising sound energy, as if the camera is being thrown toward the subject. In the last few frames the speed collapses to a perfect, silent stop, the subject sharp and centered, and a beat of stillness lets the moment land.`,{priority:76}),
  idea('ai_video','sunrise','Cinematic','Create a peaceful sunrise cinematic sequence',`A quiet, slow sunrise: low mist lying in the valleys, the first warm light touching the highest edges, birds crossing the sky, a gentle drifting camera that never hurries. The mood is stillness and gratitude, soft golden colour, long lens compression and a generous, calm final frame.`,{tags:['travel','location','wellness'],priority:75}),
  idea('ai_video','travel-commercial','Cinematic','Turn this into a high-end travel commercial',`Create a polished travel-commercial sequence that sells the feeling of being in the referenced place. Use elegant establishing views, human-scale details where supported, smooth aerial/gimbal motion, premium natural light and a clear visual progression from discovery to desire. Never invent architectural or destination details that are not grounded by references.`,{requiresReference:true,tags:['hotel','resort','travel','location','property'],priority:85}),
  idea('ai_video','before-after','Transformation','Create a cinematic before-and-after transformation',`Create a clearly legible before-to-after transformation in one coherent visual language. Establish the original state long enough to understand it, transition with motivated camera/effect movement, then hold the improved/final state in a strong hero composition. Keep unchanged identity-critical details consistent across both states.`,{priority:73}),
  idea('ai_video','space-crashzoom','Creative','Start in space and crash-zoom into this location',`Open from a vast orbital-scale perspective and execute a dramatic but smooth crash-zoom toward the referenced location, progressively resolving atmosphere, terrain and architecture until landing on a precise ground-level cinematic shot. Preserve geographic plausibility and the actual location identity; avoid fantasy map details or geometry morphing.`,{requiresReference:true,tags:['location','property','travel'],priority:82}),
  idea('ai_video','freeze-time','Creative','Freeze time while the camera moves around the scene',`Create a stylized photoreal moment where the main action appears frozen while the camera moves smoothly through three-dimensional space. Preserve subject anatomy and object positions exactly while parallax reveals depth. Keep suspended particles or motion cues physically consistent and end by gently restoring motion.`,{priority:70}),
  idea('ai_video','world-builds','Creative','Make the environment build itself around the subject',`Keep the primary subject stable while its environment assembles around it in a choreographed premium transformation. Introduce architectural, set or environmental elements in logical layers with consistent lighting, shadows and perspective, as though the world is constructing itself. Never alter the identity of a supplied subject or product.`,{priority:69}),
  idea('ai_video','miniature-real','Creative','Transition from miniature world to real scale',`Begin with the scene presented as a convincing handcrafted or miniature-scale world, then transition seamlessly into the same composition at real scale. Use depth of field, lens behavior and camera height to sell the scale change while preserving layout and subject identity. Make the reveal elegant rather than toy-like.`,{priority:66}),
  idea('ai_video','impossible-camera','Camera','Create one impossible seamless camera move',`Design a single unbroken camera move that passes through things a camera cannot: through the eye of a ring, a keyhole and an open window, shrinking and growing between scales without a visible cut, ending exactly on the subject. Every pass-through must be smooth, continuous and physically logical in its lighting.`,{priority:83}),
  idea('ai_video','neon-night','Transformation','Wake the street with neon after rain',`A rain-soaked street at blue hour comes alive: neon signs ignite one by one, their colours smearing across wet asphalt and puddles, passers-by in silhouette, steam rising from grates. The camera glides low at street level toward the subject, every reflection coloured by the nearest sign.`,{requiresReference:true,priority:71}),
  idea('ai_video','documentary-close','Cinematic','Create an intimate documentary-style moment',`Create an observational cinematic moment with subtle handheld or stabilized realism, natural performance, authentic environmental detail and restrained lighting. Favor meaningful close/medium framing, believable imperfections and emotional presence rather than commercial gloss, while keeping the supplied subject identity exact.`,{priority:64}),
];

const PRODUCT_IMAGES: CreativeIdea[] = [
  idea('product_images','luxury-studio','Luxury','Create a luxury studio campaign around this product',`Create a premium luxury advertising photograph using the supplied product as the exact hero subject. Place it in an elegant controlled studio with sculpted directional lighting, subtle reflections, precise shadows and sophisticated negative space. Make it feel like a global-brand campaign photographed on a high-end set, not an AI approximation.`,{requiresReference:true,priority:100}),
  idea('product_images','floating-dark','Studio','Make the product float in a premium dark studio',`Place the exact product floating naturally in a deep premium studio environment. Use refined rim lighting, controlled highlights, a believable contact/ambient shadow relationship, restrained atmospheric depth and polished reflections that reveal material quality without changing the product.`,{requiresReference:true,priority:96}),
  idea('product_images','ecommerce-hero','Ecommerce','Create a clean ecommerce hero photo',`Create a conversion-focused ecommerce hero image with the exact product centered or intentionally offset on a clean neutral background. Use soft even lighting, accurate material rendering, crisp edges, realistic shadow grounding and generous safe space for responsive storefront crops. No decorative clutter.`,{requiresReference:true,priority:98}),
  idea('product_images','glossy-surface','Studio','Put this product on a glossy reflective surface',`Photograph the exact product on a premium glossy surface with a physically correct, restrained reflection. Use shaped studio light, clean highlight control, realistic contact shadows and a sophisticated background gradient. Keep the reflection supportive, not distracting.`,{requiresReference:true,priority:90}),
  idea('product_images','water-splash','Creative','Create a dramatic water splash campaign',`Freeze a high-speed splash around the product as a single still: a crisp liquid crown and suspended droplets caught at a very fast shutter, backlit so every droplet carries a bright rim of light. Keep the product dry-looking, perfectly sharp and centered on a dark gradient background, shot from a low camera angle slightly looking up. Droplet shapes must look physically believable and never cover the logo or label.`,{requiresReference:true,priority:86}),
  idea('product_images','pastel-luxury','Luxury','Create a soft luxury pastel campaign',`Place the exact product in a refined pastel campaign world with soft sculptural forms, subtle tonal layering, gentle directional light and elegant shadow design. Keep the palette sophisticated and use contrast to preserve product readability. Choose two or three harmonious pastel tones and keep everything else neutral; use soft, even, diffused light, a slightly translucent surface and gentle shadows so the product feels precious and calm.`,{requiresReference:true,priority:82}),
  idea('product_images','glass-display','Creative','Place this product inside a futuristic glass display',`Present the exact product inside a believable premium glass display or vitrined environment. Use realistic refraction, reflections and edge highlights while keeping the product unobstructed and tack sharp. Make the set futuristic but clean enough for luxury advertising.`,{requiresReference:true,priority:80}),
  idea('product_images','outdoor-lifestyle','Lifestyle','Create an outdoor lifestyle campaign for this product',`Place the exact product in a realistic outdoor context that supports its actual category and use. Use natural golden-hour or soft daylight, believable environmental interaction, premium editorial composition and shallow depth where useful. Do not invent unsupported product functions.`,{requiresReference:true,priority:88}),
  idea('product_images','magazine-ad','Luxury','Make this look like a premium magazine advertisement',`Create an editorial magazine-grade product photograph with disciplined art direction, elegant negative space, sophisticated lighting and a memorable composition. Keep the product exact and leave intentional room for later real text layout rather than generating fake typography.`,{requiresReference:true,priority:84}),
  idea('product_images','spotlight','Studio','Create a dramatic spotlight product reveal',`Use one or two carefully controlled spotlights to reveal the exact product from a darker environment. Sculpt form with clean falloff, precise highlights and realistic shadow density while preserving all label and logo details. Finish with a bold, uncluttered hero composition.`,{requiresReference:true,priority:83}),
  idea('product_images','social-four','Social','Create four social campaign directions',`Create a strong social-campaign visual direction for the exact product with bold hierarchy, mobile-friendly composition and a clear hero focal point. Keep enough layout flexibility that four distinct variations can be generated without changing product identity; vary set, crop and lighting rather than the product itself.`,{requiresReference:true,priority:77}),
  idea('product_images','real-lifestyle','Lifestyle','Place the product in a realistic lifestyle environment',`Integrate the exact product into a believable real-world scene that matches how the product would actually be used or displayed. Match perspective, contact shadows, reflections, color temperature and depth so the product feels photographed in-camera rather than pasted in.`,{requiresReference:true,priority:89}),
  idea('product_images','minimal-tech','Ecommerce','Create a minimalist premium-tech product composition',`Create an ultra-clean premium technology-style composition with the exact product, disciplined geometry, soft neutral gradients, precise edge lighting and abundant negative space. Favor calm confidence and flawless material rendering over decorative props.`,{requiresReference:true,priority:87}),
  idea('product_images','marble-shadow','Luxury','Create an elegant marble and shadow campaign',`Place the exact product on or near sophisticated marble/stone surfaces with tasteful veining, warm directional light and architectural shadow shapes. Keep the set luxurious but restrained and ensure surface reflections and contact shadows remain physically believable.`,{requiresReference:true,priority:79}),
  idea('product_images','neon-campaign','Creative','Create a futuristic neon product campaign',`Build a polished futuristic set around the exact product using controlled colored light, subtle luminous accents and reflective materials. Keep brand/product colors accurate and avoid over-saturating the product itself. The result should feel like a premium launch campaign, not a generic cyberpunk render.`,{requiresReference:true,priority:76}),
  idea('product_images','instagram-launch','Social','Make this perfect for an Instagram product launch',`Create a scroll-stopping Instagram launch image with immediate product recognition, strong 4:5/1:1-safe hierarchy, premium lighting, clean background separation and intentional negative space for real campaign copy. Preserve every identity-critical detail.`,{requiresReference:true,priority:91}),
  idea('product_images','seasonal','Lifestyle','Create a seasonal campaign while preserving the product',`Create a seasonal campaign setting that clearly communicates the requested/current season through tasteful environment, materials, light and props while the exact product remains unchanged and dominant. Avoid cliché clutter; keep the campaign premium and category-appropriate.`,{requiresReference:true,priority:72}),
  idea('product_images','floating-objects','Creative','Create a high-end floating-object composition',`Keep the exact product as the stable hero while complementary category-appropriate elements float around it in a balanced, gravity-defying composition. Use coherent shadows, depth, perspective and motion implication; never obscure branding or key product surfaces.`,{requiresReference:true,priority:78}),
  idea('product_images','behind-glass','Creative','Show the product behind frosted glass with sharp reflections',`Compose the product behind a pane of frosted and clear glass: one half of the frame softly diffused, the other half razor sharp, with a thin bright edge highlight along the glass and a faint reflection of the product in it. Cool, controlled studio light from one side, deep background, generous negative space. The product stays fully readable, its logo and label are never distorted by the glass.`,{requiresReference:true,priority:68}),
  idea('product_images','particle-appear','Creative','Make the product appear from particles',`Reveal the exact product emerging from finely controlled particles that gather around its silhouette without replacing or morphing the real product. Use realistic depth, lighting and particle falloff so the effect supports the hero object rather than hiding details.`,{requiresReference:true,priority:67}),
  idea('product_images','microscopic-out','Creative','Reveal the product from microscopic details outward',`Compose a premium campaign still inspired by an extreme material/detail study that visually resolves into the complete exact product. Preserve real textures and construction details, using macro lighting and depth to connect material craftsmanship to the final hero view.`,{requiresReference:true,priority:65}),
  idea('product_images','gravity','Creative','Create a gravity-defying product showcase',`Place the exact product in a refined gravity-defying composition with believable orientation, supporting secondary elements and carefully designed shadows/reflections that make the impossible setup feel photographically intentional. Keep the product itself perfectly undistorted.`,{requiresReference:true,priority:70}),
  idea('product_images','monochrome','Studio','Create a monochrome tonal campaign around the product',`Build a sophisticated tonal set using shades related to the product or brand while maintaining enough luminance and edge contrast to keep the exact product readable. Use sculpted light, layered surfaces and restrained shadows for a fashion-editorial finish.`,{requiresReference:true,priority:63}),
  idea('product_images','premium-shelf','Ecommerce','Create a premium retail shelf hero image',`Place the exact product in a clean high-end retail display context with realistic scale, shelf lighting and depth. Keep surrounding products/props abstract or category-neutral so nothing creates fake competing brands or unsupported packaging. Keep the shelf environment believable: a clean retail fixture, tidy spacing, softly blurred signage and crisp product facing, with the hero product slightly forward and lit as the clear focal point.`,{requiresReference:true,priority:62}),
];

const PRODUCT_VIDEO: CreativeIdea[] = [
  idea('product_video','luxury-360','Luxury','Create a luxury 360° product reveal',`Create a premium cinematic commercial centered entirely on the supplied product. Begin with a mysterious authentic detail, then reveal the complete product through a smooth motion-control orbit. Use premium studio lighting, realistic reflections, physical shadows and controlled depth of field. Finish on a clean international-campaign hero shot.`,{requiresReference:true,priority:100}),
  idea('product_video','assemble','Reveal','Make the product assemble itself cinematically',`Create a cinematic assembly reveal where components or visual layers come together around the exact supplied product without altering its true geometry or branding. Use precise choreographed motion, physically plausible spacing and a final seamless transition into the untouched complete product.`,{requiresReference:true,priority:91}),
  idea('product_video','impact-drop','Dynamic','Drop the product into frame with a dramatic impact',`Open on a prepared premium set, then bring the exact product into frame with a controlled dramatic drop or landing. Use believable mass, impact timing, dust/splash/light reaction appropriate to the surface, and stabilize into a sharp hero frame without deforming the product.`,{requiresReference:true,priority:88}),
  idea('product_video','smoke-reveal','Reveal','Reveal the product through smoke and light',`Start with the exact product partially concealed by realistic volumetric haze and narrow light. Move the camera and lights in a coordinated reveal that progressively exposes silhouette, material and branding, then clear the atmosphere for a crisp final hero shot.`,{requiresReference:true,priority:89}),
  idea('product_video','floating','Luxury','Create a floating product commercial',`Make the exact product float with subtle believable rotation in a premium studio. Use consistent perspective, controlled momentum, elegant rim light and realistic reflections/shadows on nearby surfaces. Reveal key material details before settling into a stable hero composition.`,{requiresReference:true,priority:95}),
  idea('product_video','viral-tiktok','Social','Create a viral TikTok product reveal',`Create a fast premium vertical-first product reveal with a strong first-second hook, immediate product recognition, purposeful camera motion and rhythmic cuts/effects that never compromise the exact product identity. End on a clean frame designed for a real CTA overlay.`,{requiresReference:true,priority:97}),
  idea('product_video','slow-motion','Luxury','Make a premium slow-motion commercial',`Create a refined slow-motion product film using macro details, graceful motion, carefully controlled highlights and tactile material emphasis. Maintain perfect product consistency between shots and use pacing that builds anticipation toward a pristine final hero shot.`,{requiresReference:true,priority:90}),
  idea('product_video','macro-film','Reveal','Create a macro-detail product film',`Build the commercial from authentic extreme close details of the exact product—material texture, hardware, stitching, finish or packaging details—then progressively widen until the complete product is revealed. Keep macro geometry accurate and lighting consistent across the reveal.`,{requiresReference:true,priority:93}),
  idea('product_video','future-launch','Creative','Turn this into a futuristic product launch',`Create a premium future-facing launch environment around the exact product using dimensional light, restrained holographic accents and sophisticated motion graphics without generating fake text. Let the world react to the product while the product itself remains unchanged and sharply recognizable.`,{requiresReference:true,priority:83}),
  idea('product_video','fashion-campaign','Luxury','Create an elegant fashion-style campaign video',`Direct the exact product as the hero of an editorial fashion campaign with confident compositions, smooth lens movement, tactile close-ups, elegant lighting and deliberate pacing. Keep styling sophisticated and avoid visual effects that distort shape, labels or materials.`,{requiresReference:true,tags:['shoe','fashion','clothes','bag'],priority:86}),
  idea('product_video','water-emerge','Dynamic','Make the product emerge from water',`Open underwater in blue-green light with drifting caustics and rising bubbles. The product rises slowly toward the surface, breaks through it in slow motion with water sheeting off its form, then settles into a clean hero frame as the camera tilts up to follow it. Keep the product fully intact and its branding crisp the moment it clears the surface.`,{requiresReference:true,priority:79}),
  idea('product_video','world-build','Creative','Build a cinematic environment around the product',`Keep the exact product locked as the central hero while a premium environment assembles around it in choreographed layers. Match perspective, shadows, reflections and lighting as each element arrives; the environment should amplify the product category and brand mood without changing the product.`,{requiresReference:true,priority:82}),
  idea('product_video','package-open','Reveal','Make the packaging open into a premium reveal',`Use the real supplied packaging/product identity to create a believable opening reveal. Let package movement feel mechanically plausible, preserve printed branding and proportions, reveal the product cleanly without redesigning it, and finish with package and product arranged in a premium hero composition.`,{requiresReference:true,priority:84}),
  idea('product_video','clean-minimal','Minimal','Create a clean minimal commercial',`Create a disciplined minimal product film on a simple premium set. Use smooth motion-control camera moves, precise light changes, clean shadows and only essential transitions. Give the exact product uninterrupted visual priority and end with generous negative space.`,{requiresReference:true,priority:94}),
  idea('product_video','high-energy','Social','Create a high-energy social ad',`Build a high-energy short social commercial with immediate product recognition, fast but readable shot progression, purposeful match cuts, dynamic camera moves and a final confident hero hold. Keep every frame grounded in the exact supplied product; energy must come from editing and cinematography, not identity distortion.`,{requiresReference:true,priority:87}),
  idea('product_video','detail-to-hero','Reveal','Show the product from detail to hero shot',`Open on one distinctive real product detail, move through two or three meaningful material/feature views, then reveal the full exact product with a smooth visual payoff. Use consistent light and geometry so every detail clearly belongs to the same item.`,{requiresReference:true,priority:92}),
  idea('product_video','brand-launch','Luxury','Turn this into a luxury brand launch',`Shape a slow, emotional brand-launch film: restrained pacing, long graceful dolly and crane moves, deep shadows with a single warm key light, tactile close-ups of materials and craftsmanship, and a final unhurried hero shot held long enough to feel confident. No fast cuts, no gimmicks; the feeling is quiet prestige.`,{requiresReference:true,priority:96}),
  idea('product_video','glass-break','Dynamic','Make the product break through a glass-like surface',`Start on a pristine glass-like wall with the product silhouetted behind it. In ultra slow motion the product pushes through, fracturing the surface into thousands of glittering shards that hang in the air and catch the light, while the camera pushes in and settles on a perfectly sharp hero frame. The product itself is never damaged, deformed or covered by shards.`,{requiresReference:true,priority:70}),
  idea('product_video','particles','Creative','Make the product materialize from particles',`Begin with a refined field of particles that progressively resolves around the silhouette of the exact product, then transition to the untouched real product for the remainder of the shot. Keep brand marks and physical details protected from generative morphing.`,{requiresReference:true,priority:68}),
  idea('product_video','pedestal-orbit','Minimal','Orbit a premium pedestal reveal',`Place the exact product on a clean architectural pedestal and execute a subtle coordinated pedestal/camera orbit. Use changing highlights to reveal material quality, maintain stable geometry and finish in the strongest front/three-quarter hero angle.`,{requiresReference:true,priority:80}),
  idea('product_video','shadow-play','Creative','Reveal the product with moving light and shadows',`Keep the exact product stable while carefully designed light and shadow movement travels across the set and product surfaces, progressively revealing shape and material. Use realistic light direction and keep labels/logos readable at the final reveal.`,{requiresReference:true,priority:76}),
  idea('product_video','new-drop','Social','Create a premium new-drop campaign',`Build a high-energy limited-drop teaser: rhythmic cuts that land on the beat, hard strobe-like light flashes revealing the product in sharp fragments, quick macro details, one bold push-in, then a locked-off hero frame as the energy releases. Urgent and exclusive in feeling, always clean enough that the product is recognizable.`,{requiresReference:true,priority:85}),
  idea('product_video','one-take','Creative','Reveal this product in one seamless camera move',`Design one continuous shot that begins on an authentic detail, glides around or past the exact product, changes scale smoothly and resolves on the complete hero composition without visible cuts. Keep the motion physically achievable and the product geometry locked.`,{requiresReference:true,priority:81}),
  idea('product_video','lifestyle-transition','Dynamic','Transition from studio hero to real lifestyle use',`Begin with the exact product in a clean studio hero setup, then transition seamlessly into a believable lifestyle context appropriate to the product category. Preserve scale, orientation, color and identity across the transition; never imply unsupported functionality.`,{requiresReference:true,priority:75}),
];

const INTERIOR_DESIGN: CreativeIdea[] = [
  idea('interior_design','existing-space-redesign','Interior','Redesign this exact space without changing its architecture',`Create a high-end architectural interior redesign from the supplied photos and references. Keep the exact footprint and visible architecture while replacing finishes, furniture, colors and lighting according to the user's direction. Analyze the room from every supplied view before designing. Preserve ceiling height, roof shape, curves, openings and circulation.`,{requiresReference:true,tags:['home','shop','office','real-estate','room','architecture'],priority:100}),
  idea('interior_design','engineer-concept','Technical','Turn this into a professional engineer-style interior concept',`Create a professional architectural concept visualization based on the supplied photos, sketches, plans and dimensions. Show the proposed layout, ceiling/gypsum treatment, material transitions, lighting positions and built-in elements with disciplined geometry and presentation-quality realism. Treat measurements and structural constraints as source data, not decoration.`,{requiresReference:true,tags:['engineer','architect','plan','measurements','shop','real-estate'],priority:99}),
  idea('interior_design','shop-fitout','Commercial','Design a complete retail shop fit-out',`Redesign the supplied retail/commercial space as a complete professional fit-out. Preserve the exact shell and dimensions, then develop customer circulation, display walls, counters, storage, signage zones, ceiling/gypsum details, practical lighting and premium material hierarchy. Keep the result buildable-looking and consistent with the supplied space.`,{requiresReference:true,tags:['shop','retail','store','commercial'],priority:98}),
  idea('interior_design','real-estate-staging','Real Estate','Create a premium real-estate interior proposal',`Transform the supplied property into a polished real-estate interior proposal while preserving actual room proportions, openings and architectural features. Use furniture at realistic scale, coherent finishes, layered lighting and a refined material palette. Make the result suitable for client presentation and property marketing without inventing rooms or changing the shell.`,{requiresReference:true,tags:['real-estate','villa','apartment','property'],priority:96}),
  idea('interior_design','ceiling-lighting','Ceiling','Design the ceiling, gypsum and lighting system',`Focus on the supplied ceiling/roof geometry and develop a premium ceiling concept with gypsum details, coves, linear lighting, magnetic/track lighting, spots and indirect illumination where appropriate. Preserve ceiling height, beams, curves and structural constraints visible in the references. Make light sources physically plausible and coordinated with the interior.`,{requiresReference:true,tags:['ceiling','gypsum','linear','magnetic','lighting','roof'],priority:97}),
  idea('interior_design','materials-board','Materials','Create a complete material and finish direction',`Develop a cohesive architectural material direction for the exact supplied space: flooring, walls, ceiling, joinery, stone, wood, metal, glass and upholstery as appropriate. Preserve geometry and use realistic scale, seams, edge conditions and light response. Present the result as a premium design proposal rather than random decoration.`,{requiresReference:true,tags:['materials','stone','wood','marble','joinery'],priority:88}),
  idea('interior_design','before-after','Transformation','Create a precise before-and-after interior transformation',`Create a clear before-and-after transformation of the exact supplied space. Keep camera position, perspective, room dimensions and architectural shell aligned between the original and proposed design so the client can directly compare what changed. Highlight finishes, furniture, ceiling and lighting changes without changing unrelated geometry.`,{requiresReference:true,priority:94}),
  idea('interior_design','walkthrough','Video','Create a professional interior walkthrough',`Create one continuous premium architectural walkthrough of the proposed interior. Camera height, lens, room scale and spatial relationships must remain physically consistent. Move through the actual supplied layout, reveal the strongest design details, show ceiling and lighting treatment, and finish on a clear hero view. Do not invent corridors, rooms or openings that are not supported by references.`,{requiresReference:true,tags:['tour','walkthrough','real-estate','architecture'],priority:100}),
  idea('interior_design','cinematic-real-estate','Video','Create a cinematic real-estate interior tour',`Create a polished real-estate film from the proposed interior. Use slow stabilized camera movement, natural daylight plus designed practical lighting, realistic materials and carefully chosen reveals. Preserve exact room geometry and keep furniture scale believable throughout the continuous sequence.`,{requiresReference:true,tags:['real-estate','property','villa','apartment'],priority:92}),
  idea('interior_design','luxury-modern','Style','Design a luxury modern interior',`Develop a sophisticated contemporary interior using the supplied architecture as the immutable base. Favor disciplined proportions, premium materials, layered warm/cool lighting, custom joinery and restrained furniture. Preserve the actual shell, openings and dimensions while making the design feel internationally high-end.`,{requiresReference:true,priority:91}),
  idea('interior_design','minimalist','Style','Design a refined minimalist interior',`Create a calm minimalist interior with clean planes, concealed storage, restrained materials, integrated lighting and precise furniture placement. Preserve all supplied architectural constraints and dimensions. Every element should have a reason and believable scale; avoid empty-looking or impractical spaces.`,{requiresReference:true,priority:86}),
  idea('interior_design','multiple-angles','Technical','Generate consistent design views from multiple angles',`Generate a consistent architectural design set from the supplied references. Maintain the same walls, openings, ceiling, floor, furniture dimensions and materials across each requested viewpoint. Treat the first reference as geometry evidence and all additional references as cross-checks; never let a new camera angle silently change the space.`,{requiresReference:true,priority:98}),
  idea('interior_design','boutique-store','Commercial','Design a boutique clothing store interior',`Design a boutique clothing store with a clear entrance sequence: a feature display at the front, rails and shelving with generous spacing, fitting rooms at the rear with flattering light, and a compact checkout point. Material palette of warm timber, brushed metal and soft textile, layered lighting that makes colour look true, and a single memorable feature wall.`,{tags:['shop','store','boutique','clothes','fashion','retail'],priority:92}),
  idea('interior_design','cafe-interior','Commercial','Design a warm modern cafe interior',`Design a cafe built around its counter: a welcoming service bar, a mix of window seats, communal table and soft corners, warm layered lighting, durable hospitality finishes, plants and a calm acoustic feel. Keep circulation clear between the entrance, counter and seating.`,{tags:['cafe','coffee','restaurant','food'],priority:88}),
  idea('interior_design','clinic-reception','Commercial','Design a calm clinic reception and waiting area',`Design a clinic reception that feels clean, calm and trustworthy: a clear front desk, comfortable waiting seats with good privacy, soft indirect lighting, natural materials and an easily readable layout from the entrance to the consulting rooms. Surfaces must feel hygienic and easy to maintain.`,{tags:['clinic','dental','medical','salon','spa'],priority:84}),
  idea('interior_design','bedroom-retreat','Style','Redesign this bedroom as a calm retreat',`Redesign the bedroom as a restful retreat: a well-proportioned bed wall with layered headboard lighting, soft textiles, concealed storage, warm dimmable lighting and a restrained palette. Keep the windows, doors and fixed elements exactly where they are.`,{tags:['bedroom','home','villa'],priority:80}),
  idea('interior_design','kitchen-redesign','Style','Create a warm, practical kitchen redesign',`Redesign the kitchen around an efficient work triangle: tall storage on one wall, a generous worktop with task lighting, a durable splashback and a hard-wearing floor. Keep openings and plumbing positions as they are, and choose materials that are easy to clean and age well.`,{tags:['kitchen','home','apartment'],priority:80}),
  idea('interior_design','home-office','Style','Design a home office that feels focused',`Design a home office that supports long, focused work: a desk positioned for daylight without glare, a clean wall of shelving, acoustic softness, task and ambient lighting and one inspiring accent. Calm, tidy and personal rather than corporate.`,{tags:['office','home','study'],priority:76}),
  idea('interior_design','hotel-bathroom','Luxury','Create a luxury hotel-style bathroom',`Design a bathroom with a spa feeling: large-format stone-look surfaces, a frameless walk-in shower, a floating vanity with a lit mirror, warm indirect lighting and soft towels as colour. Keep the existing drainage and openings exactly where they are.`,{tags:['bathroom','hotel','home'],priority:74}),
  idea('interior_design','three-styles','Technical','Show the same room in three distinct styles',`Show the exact same room, from the same camera position, designed in three clearly different styles (for example warm modern, classic and industrial), changing only finishes, furniture and lighting while the architecture stays identical. Use the same framing so the styles can be compared directly.`,{priority:78}),
];

const WEB_VIDEO: CreativeIdea[] = [
  idea('web_video','premium-launch','Launch','Turn this website into a premium launch trailer',`Create a polished launch film for this exact website. Open with the strongest authentic brand/UI hook, reveal the most important pages or features through cinematic interface movement, focus on genuine benefits rather than random scrolling, and finish with a clear real call-to-action drawn from the site. Use tasteful depth and premium motion design while keeping the real interface recognizable.`,{priority:100}),
  idea('web_video','global-tech','Launch','Make this website feel like a global tech launch',`Present the real website like a global technology launch: confident opening, clean dimensional UI reveals, precise motion, high-end lighting/depth treatment and a structured progression from value proposition to core workflow to CTA. Keep actual website screens and claims intact.`,{tags:['saas','software','app','platform'],priority:94}),
  idea('web_video','feature-tour','Product Tour','Show the best features in a cinematic product tour',`Identify the strongest real features visible in the captured website and create a cinematic guided tour that gives each feature enough screen time to understand. Use smooth focus moves, intelligent zooms and clean transitions between real UI states, ending on the most important action.`,{priority:96}),
  idea('web_video','viral-reel','Social','Turn this website into a viral Reel',`Create a premium short-form Reel from the real website with a strong first-second hook, fast readable UI highlights, bold but tasteful pacing and a memorable CTA. Keep essential interface text legible and avoid gimmicks that obscure how the site actually works.`,{priority:91}),
  idea('web_video','3d-showcase','3D','Create a premium 3D website showcase',`Place real captured website screens into a sophisticated dimensional presentation with subtle perspective, layered depth, premium camera motion and realistic light/shadow. Screens must remain readable and undistorted; use 3D framing to elevate the real site, not replace it.`,{priority:88}),
  idea('web_video','floating-devices','3D','Make the website appear inside floating devices',`Present the real website inside a small set of premium floating device frames sized appropriately for each captured desktop/mobile screen. Use realistic perspective, reflections and depth while camera motion reveals different real site sections. Keep devices secondary to the actual interface.`,{priority:87}),
  idea('web_video','problem-solution','Conversion','Create a problem-to-solution website advertisement',`Build a concise narrative that establishes the customer problem using only claims supported by the website, then reveal this exact website as the solution, demonstrate the strongest real workflow/benefit and finish on the site's genuine conversion action. Keep the story specific and credible.`,{priority:95}),
  idea('web_video','homepage-story','Brand Story','Turn the homepage into a cinematic brand story',`Use the real homepage structure as a narrative backbone: opening proposition, key visual/benefit, proof or product/service detail, then CTA. Transform scrolling and section changes into one cohesive cinematic brand story while preserving the website's actual visual identity.`,{priority:90}),
  idea('web_video','conversion-social','Conversion','Create a fast conversion-focused social ad',`Create a direct-response social video from the real website. Hook immediately with the strongest authentic value proposition, show the minimum real UI needed to prove it, emphasize one or two genuine benefits and end with a clean CTA from the site. Optimize pacing for mobile while keeping text readable.`,{priority:93}),
  idea('web_video','easy-to-use','Product Tour','Show how easy this website is to use',`Demonstrate a real simple user path through the captured site, using clear cursor/focus-style movement and smooth transitions to show how a visitor completes an important action. Keep every step grounded in the actual UI and avoid inventing interactions that were not captured.`,{priority:86}),
  idea('web_video','luxury-web','Brand Story','Create a luxury commercial for this website',`Turn the real website into a restrained luxury commercial with elegant pacing, premium depth, carefully timed interface reveals and sophisticated visual hierarchy. Preserve the site's actual typography/colors and avoid overselling; let real imagery and interface details feel expensive through direction.`,{priority:82}),
  idea('web_video','app-launch','Launch','Turn this website into an app-style product launch',`Present the real website as a polished digital product launch, emphasizing its interface system, workflow and primary outcome through crisp screen transitions and device-aware compositions. Use app-launch pacing while never pretending the website has screens or features not captured.`,{tags:['saas','app','software'],priority:85}),
  idea('web_video','ui-alive','3D','Make the UI come alive around the viewer',`Use the real interface as layered visual material: cards, sections and screenshots can lift into dimensional space, reassemble and guide the viewer through the site's value. Preserve actual UI pixels and text on important elements; animation should clarify hierarchy instead of inventing new interface content.`,{priority:84}),
  idea('web_video','linkedin','Social','Create a clean LinkedIn launch video',`Create a professional LinkedIn-ready launch video using the real website. Lead with a concise business value proposition, show the strongest authentic workflow or differentiator, use restrained premium motion and end with a clear next step. Keep pacing confident, informative and readable without hype.`,{priority:89}),
  idea('web_video','tiktok-web','Social','Create a bold TikTok website commercial',`Create a vertical-first TikTok commercial from the actual site with an immediate visual hook, quick but understandable screen reveals, energetic transitions and a clear payoff. Keep real UI readable and use camera/editing energy instead of fake interface text or unsupported claims.`,{priority:88}),
  idea('web_video','future-interface','3D','Turn this website into a futuristic interface reveal',`Place the real website screens in a clean futuristic dimensional environment with subtle luminous accents, depth and motion. Keep the actual interface as the source of truth and avoid fake holographic text; the futuristic treatment should frame and reveal the real product, not redesign it.`,{priority:78}),
  idea('web_video','web-to-real','Brand Story','Create a cinematic website-to-real-world transition',`Begin on the real website on a screen, then use one precise match-cut so the screen becomes the real place, product or service it describes, and end in a confident hero shot of that real world. A single clear transition is the idea; keep everything else restrained and the website's true branding visible at the start.`,{priority:80}),
  idea('web_video','customer-journey','Conversion','Show the customer journey from visit to action',`Use real captured pages to demonstrate the customer journey from landing/discovery through the most important consideration step to the website's genuine action such as buy, book, contact, sign up or order. Keep the sequence accurate and conversion-focused.`,{priority:97}),
  idea('web_video','before-after-discovery','Brand Story','Create a before-discovering vs after-discovering story',`Create a concise contrast narrative showing the user's problem/state before discovering the website and the outcome enabled by the website afterward, using only outcomes supported by real site content. Make the website reveal the turning point and end with its authentic CTA.`,{priority:79}),
  idea('web_video','location-drone-site','Brand Story','Fly over the location, then reveal the website',`If reliable location imagery is available, begin with a realistic drone-inspired establishing sequence that preserves the actual physical place, then transition seamlessly into the real website interface and highlight the most important booking/menu/property/service action. If the physical place is not visually grounded, keep the opening abstract rather than inventing architecture.`,{requiresReference:true,tags:['hotel','resort','restaurant','cafe','property','real-estate','venue','gym','clinic','store','location'],priority:99}),
  idea('web_video','destination','Brand Story','Turn this place into a luxury destination commercial',`Use reliable place imagery and the real website together to create a luxury destination film: establish the actual location, reveal authentic atmosphere/details, then connect naturally into the real site for booking, menu, service or contact. Never fabricate exact architecture or amenities absent from the references/site.`,{requiresReference:true,tags:['hotel','resort','restaurant','travel','location'],priority:88}),
  idea('web_video','scroll-one-move','3D','Turn scrolling into one continuous cinematic camera move',`Transform the real website's captured section sequence into one continuous cinematic movement that feels like the camera travels through the page rather than jump-cutting between screenshots. Preserve layout/text fidelity and use depth/parallax to connect authentic sections smoothly.`,{priority:83}),
  idea('web_video','screen-world','Creative','Walk through the website as a series of real-world sets',`Walk the camera continuously through three or four physical sets, each one built from a real section of the website: the hero becomes an entrance hall, the features become a gallery of objects, the proof becomes a warm room full of people. Keep the real branding, colours and copy of each section recognizable as the set it came from.`,{priority:76}),
  idea('web_video','sections-real','Creative','Make website sections become real-world scenes',`Use selected real website sections as portals into tasteful real-world visualizations of the products/services they genuinely represent. Transition back and forth while preserving exact UI screenshots for important information. Do not invent products, locations or claims not supported by the site.`,{priority:74}),
  idea('web_video','ecom-shopping','Conversion','Turn the store into a premium shopping commercial',`Use real ecommerce pages and product captures to build a premium shopping commercial from discovery to product detail to cart/checkout intent. Make actual products the visual heroes, keep prices/text only when captured clearly, and end on the real purchase action.`,{tags:['ecommerce','shop','store','product'],priority:98}),
  idea('web_video','best-sellers','Product Tour','Create a cinematic best-sellers showcase',`Select the strongest real products visible in the captured store and showcase them with premium screen motion, focused product crops and clean transitions while preserving their actual appearance. Avoid inventing rankings or “best seller” claims unless the website supports them; otherwise frame them as featured products.`,{tags:['ecommerce','shop','store'],priority:87}),
  idea('web_video','saas-workflow','Product Tour','Show the product workflow clearly and cinematically',`Use the actual SaaS/software screens to show one meaningful end-to-end workflow with a clear start, key interaction/result and payoff. Keep the sequence faithful to captured UI and use premium motion to explain rather than distract. Show the real interface in motion: one clear task from start to finish, natural cursor movement, key results emphasised by gentle zooms and a calm closing frame on the finished outcome.`,{tags:['saas','software','platform','dashboard'],priority:98}),
  idea('web_video','restaurant-order','Conversion','Make the menu come alive as dishes being served',`Turn the real menu and food photography from the website into an appetizing sequence: steam rising, sauces poured in slow motion, hands placing each dish on a table, a final spread that looks irresistible. Use only dishes, branding and venue details that actually appear on the website, then close on the ordering moment.`,{tags:['restaurant','cafe','food'],priority:96}),
  idea('web_video','property-reveal','Brand Story','Create a cinematic drone property reveal',`Use reliable property imagery to establish the actual property with a realistic aerial-inspired reveal, then transition into the real listing website for authentic details and the contact/booking action. Preserve true exterior/interior features and never invent architecture beyond the supplied listing/reference.`,{requiresReference:true,tags:['real-estate','property','villa','listing'],priority:97}),
];

const SCENARIO: CreativeIdea[] = [
  idea('scenario','founder','Performance','Have the founder explain the product naturally',`Create a natural founder-led explanation in a clean believable setting. The speaker should sound conversational rather than scripted, use concise sentences, demonstrate or reference only real product benefits, and maintain comfortable eye contact and realistic gestures. End with a short authentic next step.`,{priority:95}),
  idea('scenario','two-person','Performance','Create a natural two-person product conversation',`Stage a believable two-person conversation where one person has a real question/problem and the other naturally explains the product/service. Use reaction shots, subtle overlaps and human pacing rather than alternating monologues. Keep claims grounded in the user's brief.`,{priority:92}),
  idea('scenario','testimonial','Social','Create a warm customer testimonial scene',`Create an authentic customer-testimonial style scene with natural phrasing, specific but supported benefits and restrained emotion. Avoid exaggerated claims or fake statistics. Use intimate framing and believable ambient movement so it feels captured, not performed by an ad actor.`,{priority:90}),
  idea('scenario','podcast','Social','Turn this into a premium podcast-style clip',`Stage the message as a polished conversational podcast/interview excerpt with natural turn-taking, clean close/medium coverage, subtle camera changes and high-quality studio ambience. Keep the content concise enough to fit the selected duration without rushed speech.`,{priority:82}),
  idea('scenario','demo-dialogue','Performance','Explain the workflow while using the product',`Create a performance-led demonstration where the speaker naturally uses or points to the real product/interface while explaining the key workflow. Keep actions synchronized with what is being said and do not invent steps or features unsupported by the prompt/reference.`,{priority:88}),
  idea('scenario','street-interview','Social','Create a polished street-interview style reaction',`Create a believable quick street-interview style exchange with natural body language, concise question/answer structure and documentary camera energy. Keep audio/performance clean and avoid caricature or exaggerated reactions. Keep the setting real and busy: shallow-focus pedestrians behind, a handheld microphone partly in frame, natural interruptions and one honest laugh so the answers feel spontaneous.`,{priority:70}),
  idea('scenario','problem-solution','Performance','Act out the problem, then reveal the solution',`Create a compact scene that first shows the user's described problem through believable action/dialogue, then introduces the product/service as the solution and demonstrates the supported outcome. Make the transition clear and keep the final line concise.`,{priority:85}),
  idea('scenario','direct-camera','Performance','Deliver a confident direct-to-camera launch message',`Create a confident direct-to-camera launch performance with one strong opening line, two or three concise supporting points and a clean close. Use natural gestures, professional but human delivery and subtle cinematic camera movement without overacting.`,{priority:87}),
  idea('scenario','walk-and-talk','Performance','Walk and talk through the space while explaining',`The speaker walks through the real space while explaining, in one smooth tracking shot that stays slightly ahead of them: natural gestures, relaxed eye contact with the camera now and then, and small spoken pauses. The space reveals itself behind them as they move, with warm practical light and a shallow depth of field.`,{priority:84}),
  idea('scenario','expert-interview','Performance','Create an expert interview with natural cutaways',`Stage a calm two-camera interview: the expert answers a single question in a steady medium shot with a closer reaction angle for emphasis, and the dialogue is natural and unscripted in feel. Soft window light, a lived-in background, subtle handheld breathing, and a short cutaway to the topic being discussed.`,{priority:82}),
  idea('scenario','customer-story','Social','Tell a before-and-after customer story in conversation',`A satisfied customer talks to a friend off camera, describing life before and after using the product, with honest hesitations and a real smile when they reach the result. Keep the setting everyday and the tone warm; the benefit is shown through how they describe it, never through exaggerated claims.`,{priority:80}),
  idea('scenario','founder-diary','Performance','Film a behind-the-scenes founder diary clip',`A founder records a casual diary-style clip in their real workspace between tasks: handheld, close and personal, speaking candidly about one thing they are proud of this week, glancing at the work behind them. Imperfect framing and natural room tone make it feel genuine.`,{priority:78}),
  idea('scenario','colleague-demo','Performance','Stage a friendly product demo between two colleagues',`Two colleagues sit side by side: one shows the product while the other asks the questions a real newcomer would ask, with quick, natural back-and-forth and a moment where the second one reacts with surprise. Two-shot framing, soft office light, gentle push-ins on each speaker as they talk.`,{priority:79}),
  idea('scenario','news-announcement','Social','Deliver a news-style announcement',`A presenter delivers a crisp, trustworthy announcement straight to camera in a clean studio setting: composed posture, clear pacing, confident hand gestures, subtle lower-key lighting with a soft background glow. The tone is clear and professional, with no sensational claims.`,{priority:72}),
  idea('scenario','simple-explainer','Performance','Have a teacher explain one idea in the simplest way',`A friendly teacher explains a single idea in plain words, using one small prop or a quick sketch to make it clear, checking that the viewer follows with a warm look to camera. Bright classroom-like light, medium shot with a gentle push-in at the key sentence, patient and encouraging performance.`,{priority:76}),
  idea('scenario','friend-recommendation','Social','Create a cozy recommendation from one friend to another',`Two friends on a sofa, one casually recommending the product to the other, with overlapping natural speech, a laugh and an honest, specific reason they like it. Warm evening lamp light, handheld framing at eye level, a lived-in living room.`,{priority:74}),
  idea('scenario','unboxing-reaction','Social','Film a genuine unboxing reaction with spoken thoughts',`A person opens the package at a table and reacts as they go: surprise at the packaging, curiosity at the first look, spoken first impressions that sound spontaneous. Close hands-and-product shots mix with medium shots of their face; bright natural daylight and a tidy but real desk.`,{requiresReference:true,priority:77}),
  idea('scenario','one-question','Performance','Answer the one question everyone asks',`The speaker looks into camera and answers the single question customers ask most, directly and briefly: a short setup, a clear answer, a reassuring beat. Minimal background, steady medium close-up, natural vocal emphasis and one small gesture to underline the answer.`,{priority:75}),
];

const ARCHITECTURE: CreativeIdea[] = [
  idea('architecture','site-concept','Concept','Design a contemporary building that fits this exact plot',`Design a well-proportioned contemporary building for the supplied plot. Read the street, neighbours, orientation and terrain from the site references, keep the footprint inside the plot minus its setback and respect the stated number of floors. Give it a clear massing idea, a coherent facade rhythm, honest materials and landscaping that belongs to the site.`,{requiresReference:true,tags:['plot','land','site','building','concept'],priority:100}),
  idea('architecture','place-my-building','Reference','Place my building design on this site',`Place the supplied building reference on the supplied site as the finished design. Keep its massing, facade rhythm, materials and roof form exactly; adapt only scale and orientation to the plot, respect the setback and floor count, and integrate it believably with the street, neighbours and terrain.`,{requiresReference:true,tags:['reference','render','elevation','design'],priority:99}),
  idea('architecture','family-villa','Residential','Design a modern family villa for this plot',`Design a modern detached family villa suited to the plot and its climate: clear entrance sequence, generous glazing where the orientation allows it, shaded terraces, a garden that uses the remaining plot, parking placed sensibly and a calm, high-quality material palette.`,{requiresReference:true,tags:['villa','house','residential','family'],priority:96}),
  idea('architecture','apartment-block','Residential','Design a mid-rise apartment building',`Design a mid-rise apartment building that uses the buildable footprint efficiently: a legible base, repeating balcony rhythm, a strong corner or crown, ground-floor entrance and landscaping. Keep the floor count exact and floor heights believable.`,{requiresReference:true,tags:['apartment','residential','floors','building'],priority:94}),
  idea('architecture','shops-and-offices','Commercial','Design a commercial building with ground-floor shops',`Design a commercial building with active ground-floor shopfronts, clear entrances, a clean facade system for the upper floors and quiet signage zones (no readable lettering). Respect the plot, setback and floor count and relate it to the street it faces.`,{requiresReference:true,tags:['commercial','shop','retail','office'],priority:95}),
  idea('architecture','office-building','Commercial','Design a compact modern office building',`Design a compact modern office building with a regular structural grid expressed in the facade, generous daylight, a welcoming lobby at street level and roof terraces where sensible. Keep proportions credible for the stated floors and plot. Show daylight pouring into the lobby with people in silhouette at dusk; keep the facade grid crisp and the materials credible (glass, metal, stone).`,{requiresReference:true,tags:['office','commercial','corporate'],priority:88}),
  idea('architecture','mixed-use','Mixed use','Design a mixed-use building: retail below, homes above',`Design a mixed-use building with retail at street level and homes above. Separate the two entrances clearly, step the massing to suit the plot and neighbours and give the residential floors balconies or terraces. Show both lives of the building: a lively street level with people and awnings, and quieter residential floors above with warm lit windows at dusk.`,{requiresReference:true,tags:['mixed','retail','residential'],priority:90}),
  idea('architecture','local-character','Style','Design a building that respects the local architectural character',`Design a contemporary building that clearly respects the architectural character visible in the site references: proportions, materials, roof forms and openings of the neighbourhood, reinterpreted rather than copied. Choose forms, openings, materials and colour that are typical for the place (read them from the site images) and express them in a contemporary way rather than as imitation.`,{requiresReference:true,tags:['local','context','traditional','heritage'],priority:89}),
  idea('architecture','sustainable','Style','Design a sustainable building with passive cooling and shading',`Design an energy-conscious building for the climate suggested by the location: orientation-aware glazing, deep shading, cross-ventilation, a green roof or planted terraces and durable natural materials. Show the sustainable ideas through form, not labels.`,{requiresReference:true,tags:['sustainable','green','climate','passive'],priority:85}),
  idea('architecture','day-and-dusk','Presentation','Show the finished building by day and at dusk',`Present the same finished building in daylight and at blue-hour dusk, keeping every architectural detail, material and the plot identical while only the light changes. Warm interior light at dusk, natural shadows by day. Use the same camera position for both views so the light is the only difference: crisp daylight under a clear sky, then deep blue dusk with a warm interior glow.`,{requiresReference:true,tags:['dusk','night','lighting','presentation'],priority:91}),
  idea('architecture','plot-before-after','Transformation','Show the empty plot and the finished building',`Show a clear before-and-after of the exact supplied site: first the plot as it is today, then the same camera position with the finished building in place. Keep the street, neighbours, terrain and framing identical between the two. Use the same camera position for both images: first the empty plot exactly as it is, then the finished building placed on it with matching light and shadows.`,{requiresReference:true,tags:['before','after','transformation','plot'],priority:93}),
  idea('architecture','facade-options','Design','Explore a different facade for the same building',`Keep the building's massing, floor count and position on the plot and explore a different facade treatment: a new material palette, opening rhythm and shading system. Only the facade changes. Keep the massing, floor count, openings and site identical and change only the facade language between the options (materials, rhythm, depth, shading), so the variants can be compared fairly.`,{requiresReference:true,tags:['facade','material','options'],priority:84}),
  idea('architecture','walk-around','Video','Create a cinematic walk-around of the building on its site',`Create one continuous cinematic walk-around of the finished building on its real site. Start at the street, move past the entrance, circle the building at human eye level with stable, slow movement and finish on a strong hero view. Keep geometry, materials and surroundings consistent throughout.`,{requiresReference:true,tags:['video','walk','walkthrough','tour'],priority:97}),
  idea('architecture','drone-reveal','Video','Drone reveal of the finished building on its plot',`Create a smooth drone reveal of the finished building: start high over the neighbourhood, descend toward the plot and orbit gently to reveal massing, roof, landscaping and the relationship to the street. Physically plausible motion, no warped geometry.`,{requiresReference:true,tags:['video','drone','aerial','reveal'],priority:96}),
  idea('architecture','shop-fit-out','Retail','Design a clothes shop inside this existing building',`The customer wants a shop inside the building shown, not a new building. Keep the existing shell, structure and facade exactly as they are and design the finished clothing shop for a ground-floor unit: entrance, display window, rails and fitting rooms, till point, lighting and finishes, shown from inside and from the street. Never replace the building.`,{tags:['shop','store','boutique','clothes','fashion','retail','apartment','unit'],priority:95}),
  idea('architecture','shopfront','Retail','Design a new shopfront and entrance for this unit',`Design only the shopfront of the existing unit: a glazed display window, a clear entrance, a signage zone with no readable lettering, and warm evening light spilling onto the pavement. The building around it and its neighbours stay exactly as they are; show it from the street at eye level and at dusk.`,{tags:['shopfront','storefront','sign','facade','retail'],priority:90}),
  idea('architecture','facade-renovation','Renovation','Renovate the facade of this existing building',`Renovate only the exterior skin of the existing building: new cladding, window rhythm, balconies and entrance treatment in a coherent contemporary language. Keep the massing, floor count, openings and structure exactly as they are, and show the before-and-after relationship through the same camera angle.`,{tags:['renovate','facade','refurbish','old','existing'],priority:88}),
  idea('architecture','add-floors','Extension','Add two floors to this existing building',`Design a vertical extension of two additional floors on the existing building: a lighter, recessed upper volume that respects the existing facade rhythm, a clear structural logic and a roof terrace. Keep the lower floors exactly as they are and show the join between old and new honestly.`,{tags:['extension','floors','add','existing'],priority:82}),
  idea('architecture','boutique-hotel','Hospitality','Design a boutique hotel on this plot',`Design a small boutique hotel: an inviting arrival court, a double-height lobby seen through glazing, guest floors with a repeated balcony or loggia rhythm and a roof terrace or garden. Materials should feel warm and local, with soft architectural lighting at dusk. Keep within the plot, setback and stated floor count.`,{tags:['hotel','guesthouse','hospitality'],priority:78}),
  idea('architecture','courtyard-house','Residential','Design a courtyard house for this plot',`Design a courtyard house where the rooms wrap a private open court: deep shaded verandas, cross ventilation, a calm blank street face for privacy and generous glazing toward the court. Adapt it to the local climate and keep within the plot and setback.`,{tags:['courtyard','house','villa','family'],priority:80}),
  idea('architecture','restaurant-terrace','Hospitality','Design a restaurant with a terrace on this plot',`Design a restaurant with a welcoming street face, a glazed dining hall and a shaded terrace for evening use, a discreet service side and a kitchen volume that does not dominate. Warm light at dusk, planting to soften the edges, no readable lettering on signage.`,{tags:['restaurant','cafe','terrace','food'],priority:76}),
  idea('architecture','clinic-building','Civic','Design a small clinic building on this plot',`Design a calm, accessible clinic building: a clear entrance with a covered drop-off, a reception visible through glazing, quiet consulting wings with controlled privacy and a landscaped waiting garden. Materials should feel clean and reassuring.`,{tags:['clinic','medical','dental','health'],priority:72}),
  idea('architecture','townhouse-row','Residential','Design a compact townhouse row',`Design a short row of townhouses that share a coherent facade rhythm while each keeps its own entrance, small front garden and balcony. Stagger the setbacks slightly, vary materials subtly between units and keep the roofline consistent. Respect the plot, setback and the stated floors.`,{tags:['townhouse','row','homes','residential'],priority:70}),
  idea('architecture','site-landscape','Landscape','Design the landscape and outdoor spaces for this site',`Design the outdoor spaces of the site: a clear arrival path, planting suited to the local climate, shaded seating, permeable paving and low lighting for the evening. The building on the site stays exactly as it is; only the surroundings are designed.`,{tags:['landscape','garden','courtyard','outdoor'],priority:68}),
];

export const CREATIVE_IDEAS: Record<IdeaFeature, CreativeIdea[]> = {
  ai_video: AI_VIDEO,
  product_images: PRODUCT_IMAGES,
  product_video: PRODUCT_VIDEO,
  web_video: WEB_VIDEO,
  scenario: SCENARIO,
  interior_design: INTERIOR_DESIGN,
  architecture: ARCHITECTURE,
};

const INTENT_FEATURE = {
  website: 'web_video',
  video: 'ai_video',
  photo: 'product_images',
  'product-video': 'product_video',
  scenario: 'scenario',
  interior: 'interior_design',
  architecture: 'architecture',
} as const;

export type IdeaIntent = keyof typeof INTENT_FEATURE;
export function featureForIntent(intent: IdeaIntent): IdeaFeature { return INTENT_FEATURE[intent]; }

function contextTokens(context: IdeaContext) {
  return `${context.websiteUrl ?? ''} ${context.prompt ?? ''} ${(context.referenceNames ?? []).join(' ')}`.toLowerCase();
}

function scoreIdea(item: CreativeIdea, context: IdeaContext) {
  const tokens = contextTokens(context);
  let score = item.priority;
  for (const tag of item.tags) if (tokens.includes(tag.toLowerCase())) score += 35;
  if (item.requiresReference && !context.hasReferences) score -= 14;
  if (item.requiresReference && context.hasReferences) score += 8;
  const seed = context.seed ?? 0;
  let hash = seed + 17;
  for (const ch of item.id) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
  score += (hash % 13) / 10;
  return score;
}

export function getIdeasForIntent(intent: IdeaIntent, context: IdeaContext = {}, limit = 8) {
  return [...CREATIVE_IDEAS[featureForIntent(intent)]]
    .sort((a, b) => scoreIdea(b, context) - scoreIdea(a, context))
    .slice(0, Math.max(1, limit));
}

export function referenceHintForIdea(item: CreativeIdea, context: IdeaContext) {
  return item.requiresReference && !context.hasReferences
    ? 'Add a photo or reference for a more accurate result.'
    : null;
}
